// Match Engine v3 — one calibrated score, no stacked bonus chain.
function targetTermForMatch(){return jobFilters.semester&&jobFilters.semester!=='all'&&jobFilters.semester!=='Unspecified'?jobFilters.semester:'Summer'}
function calibratedLocationFit(job){const p=state.profile,sameCity=!!(p.location&&job.location&&job.location.toLowerCase().includes(p.location.toLowerCase().split(',')[0]));switch(p.workPreference){case'remote':return job.mode==='Remote'?1:.25;case'close-home':return sameCity?1:(job.mode==='Remote'?.72:.32);case'hybrid':return job.mode==='Hybrid'?1:(job.mode==='Remote'?.65:.55);case'relocate':return job.mode==='Remote'?.78:1;default:return .72}}
function calibratedTermFit(job){const target=targetTermForMatch(),seasons=job.season||['Unspecified'];if(job.year&&job.year!==targetInternshipYear())return 0;if(job.year===targetInternshipYear()&&seasons.includes(target))return 1;if(!job.year&&seasons.includes(target))return .7;if(seasons.includes('Unspecified'))return .42;return .15}
function calibratedDataConfidence(job){const graph=jobRequirementGraph(job),hasLocation=job.location&&job.location!=='Location not listed'&&!/listed on employer page/i.test(job.location),signals=[graph.nodes.length>=3?.4:graph.nodes.length?.22:0,job.year?.18:0,(job.season||[]).some(x=>x!=='Unspecified')?.14:0,hasLocation?.14:0,(job.degreeFields||[]).length?.08:0,(job.skills||[]).filter(x=>x!=='Engineering').length?.06:0];return Math.min(1,.12+signals.reduce((a,b)=>a+b,0))}
function calibratedMatchBreakdown(job){const field=profileDiscipline(job),requirements=jobRequirementGraph(job).nodes,coverage=weightedRequirementCoverage(job),risk=hardRequirementRisk(job),location=calibratedLocationFit(job),term=calibratedTermFit(job),confidence=calibratedDataConfidence(job),profileSkillSet=new Set((state.profile.skills||[]).map(x=>x.toLowerCase())),listed=(job.skills||[]).filter(x=>x&&x!=='Engineering'),matched=listed.filter(x=>profileSkillSet.has(x.toLowerCase()));let evidence=requirements.length?coverage:(listed.length?matched.length/listed.length:.38);const raw=field*.30+evidence*.34+location*.16+term*.20;let score=raw*100;score-=risk*12;if(field<.25)score=Math.min(score,48);if(term===0)score=Math.min(score,42);if(confidence<.45)score=Math.min(score,74);else if(confidence<.62)score=Math.min(score,84);score=Math.round(Math.max(5,Math.min(96,score)));return{score,field,skills:evidence,location,term,matched,dataConfidence:confidence,skillData:requirements.length>0||listed.length>0,requirementCoverage:coverage,hardRequirementRisk:risk,requirementCount:requirements.length,model:'calibrated-v3'}}
matchBreakdown=function(job){return calibratedMatchBreakdown(job)};
match=function(job){return calibratedMatchBreakdown(job).score};
function calibratedOpportunityPriority(job){const b=calibratedMatchBreakdown(job);let priority=b.score;if(targetTermConfirmed(job))priority+=4;else if(job.year===targetInternshipYear())priority+=2;if(b.dataConfidence>=.7)priority+=2;if(state.profile.workPreference==='close-home'&&b.location>=.8)priority+=2;return priority}
opportunityPriority=function(job){return calibratedOpportunityPriority(job)};
function matchConfidenceLabel(job){const b=calibratedMatchBreakdown(job);if(b.dataConfidence>=.75&&b.requirementCount>=4)return'High listing confidence';if(b.dataConfidence>=.55)return'Moderate listing confidence';return'Limited listing data'}
function matchScoreExplanation(job){const b=calibratedMatchBreakdown(job),coverage=Math.round(b.requirementCoverage*100),risk=Math.round(b.hardRequirementRisk*100);return`${b.score}% combines field fit (${Math.round(b.field*100)}%), source-backed requirement coverage (${coverage}%), location (${Math.round(b.location*100)}%), and term (${Math.round(b.term*100)}%).${risk?` ${risk}% of weighted hard requirements are not currently supported by your evidence.`:''} ${matchConfidenceLabel(job)}.`}
