const seedJobs=[
{id:'j1',company:'Aperture Robotics',title:'Mechanical Engineering Intern',location:'Pittsburgh, PA',mode:'Hybrid',skills:['CAD','SolidWorks','Python','Mechanical Design'],preferred:['Prototyping','GD&T'],deadline:'Oct 18, 2026',source:'Sample fallback',season:['Summer'],applyUrl:'',desc:'Support mechanical design, CAD modeling, prototype testing, and engineering documentation for robotic systems.'},
{id:'j2',company:'Northstar Aerospace',title:'Engines Engineering Intern',location:'Cincinnati, OH',mode:'On-site',skills:['CAD','Thermodynamics','Excel','Mechanical Systems'],preferred:['Data Analysis','Testing'],deadline:'Oct 25, 2026',source:'Sample fallback',season:['Summer'],applyUrl:'',desc:'Assist engineers with component design, test data review, root-cause analysis, and aircraft engine development.'},
{id:'j3',company:'Forge Mobility',title:'Product Design Engineering Intern',location:'Detroit, MI',mode:'Hybrid',skills:['SolidWorks','Onshape','Prototyping','GD&T'],preferred:['Manufacturing','Testing'],deadline:'Nov 2, 2026',source:'Sample fallback',season:['Summer'],applyUrl:'',desc:'Create and revise CAD, support prototype builds, and collaborate with manufacturing and test teams.'},
{id:'j4',company:'Vector Automation',title:'Systems Engineering Intern',location:'Dayton, OH',mode:'On-site',skills:['Python','Data Analysis','Systems Engineering','Excel'],preferred:['Requirements','Testing'],deadline:'Oct 30, 2026',source:'Sample fallback',season:['Summer'],applyUrl:'',desc:'Support requirements, test planning, data analysis, and cross-functional systems verification.'},
{id:'j5',company:'Lumen Manufacturing',title:'Process Engineering Intern',location:'Cleveland, OH',mode:'On-site',skills:['Excel','Process Optimization','Data Analysis','CAD'],preferred:['Manufacturing','Lean'],deadline:'Nov 8, 2026',source:'Sample fallback',season:['Summer'],applyUrl:'',desc:'Analyze production processes, document improvements, and support fixture or workflow design.'},
{id:'j6',company:'Cascade Energy',title:'Mechanical Engineering Intern',location:'Remote',mode:'Remote',skills:['Mechanical Design','Python','Excel','CAD'],preferred:['Technical Writing','Data Analysis'],deadline:'Nov 15, 2026',source:'Sample fallback',season:['Summer'],applyUrl:'',desc:'Support design analysis, technical documentation, and data-driven engineering projects.'}
];
const INTERN_STATE_VERSION=2;
const defaultState={version:INTERN_STATE_VERSION,profile:{name:'',personalEmail:'',schoolEmail:'',school:'',major:'',grad:'',gpa:'',location:'',workPreference:'',summary:'',skills:[],resumeText:'',resumeFilename:'',evidence:[],careerGraph:{}},saved:[],apps:[],page:'dashboard'};
const schoolSuggestions=['The Ohio State University','University of Cincinnati','Case Western Reserve University','Cleveland State University','University of Akron','University of Dayton','Miami University','Ohio University','University of Toledo','University of Michigan','Michigan State University','Purdue University','University of Illinois Urbana-Champaign','Pennsylvania State University','Carnegie Mellon University','University of Pittsburgh','Georgia Institute of Technology','Virginia Tech','North Carolina State University','University of Texas at Austin','Texas A&M University','University of Wisconsin-Madison','Massachusetts Institute of Technology','Stanford University'];
const majorSuggestions=['Mechanical Engineering','Aerospace Engineering','Electrical Engineering','Computer Engineering','Computer Science','Civil Engineering','Chemical Engineering','Biomedical Engineering','Industrial and Systems Engineering','Materials Science and Engineering','Engineering Physics','Mechatronics Engineering','Robotics Engineering','Data Science','Mathematics','Physics'];
const locationSuggestions=['Cleveland, OH','Columbus, OH','Cincinnati, OH','Dayton, OH','Akron, OH','Toledo, OH','Pittsburgh, PA','Detroit, MI','Grand Rapids, MI','Chicago, IL','Indianapolis, IN','Boston, MA','New York, NY','Philadelphia, PA','Washington, DC','Charlotte, NC','Atlanta, GA','Orlando, FL','Tampa, FL','Miami, FL','Austin, TX','Dallas, TX','Houston, TX','Denver, CO','Phoenix, AZ','San Diego, CA','Los Angeles, CA','San Francisco, CA','San Jose, CA','Seattle, WA','Portland, OR','Remote'];
const gradSuggestions=[];for(let y=new Date().getFullYear();y<=new Date().getFullYear()+8;y++)for(const m of ['May','August','December'])gradSuggestions.push(`${m} ${y}`);
function options(list){return list.map(v=>`<option value="${esc(v)}"></option>`).join('')}
let state=load();
let internActiveView='dashboard',internActiveJobId=null;
let jobsData=[...seedJobs],jobsSource='fallback',jobsLoaded=false,jobsLoading=false;
let jobFilters={query:'',location:'',mode:'all',saved:false,semester:'Summer'};
function migrateState(saved={}){const next={...structuredClone(defaultState),...saved,profile:{...structuredClone(defaultState.profile),...(saved.profile||{})}};next.version=INTERN_STATE_VERSION;next.saved=Array.isArray(next.saved)?next.saved:[];next.apps=Array.isArray(next.apps)?next.apps:[];next.apps=next.apps.map(a=>({...a,status:a.status||'Interested',statusHistory:Array.isArray(a.statusHistory)?a.statusHistory:[]}));return next}
function load(){try{return migrateState(JSON.parse(localStorage.getItem('internai-demo')||'{}'))}catch{return structuredClone(defaultState)}}
function persist(){localStorage.setItem('internai-demo',JSON.stringify(state))}
function safeApplyUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:''}catch{return ''}}
function listingAvailability(job={}){const url=safeApplyUrl(job.applyUrl||'');if(job.source==='Sample fallback'||(!job.live&&!job.imported))return{available:false,label:'Sample listing',reason:'This is an illustrative sample, not a live employer opening.'};if(!url)return{available:false,label:'Application link unavailable',reason:'This employer listing does not currently provide a safe application link.'};if(job.closed===true||job.status==='closed')return{available:false,label:'Closed listing',reason:'The employer marked this posting closed. Your saved notes and drafts remain available.'};const verified=job.availabilityCheck;if(verified?.status==='unavailable'&&Date.now()-Date.parse(verified.checkedAt)<600000)return{available:false,label:'Posting unavailable',reason:'The provider no longer returns this posting at its recorded link. It may have closed or moved.'};const posted=Number(job.postedAt);if(Number.isFinite(posted)&&posted>0){const ageDays=Math.floor((Date.now()-posted)/86400000);if(ageDays>120)return{available:true,label:'Older employer listing',reason:`This posting is about ${ageDays} days old. Verify it is still accepting applications before preparing materials.`,stale:true,ageDays}}return{available:true,label:'Employer application',reason:'',stale:false}}
function listingAvailabilityNotice(job){const availability=listingAvailability(job);const fetched=job.fetchedAt&&Number.isFinite(Date.parse(job.fetchedAt))?`<div class="meta" style="margin-top:8px">Source fetched: ${esc(new Date(job.fetchedAt).toLocaleString())}. Confirm availability on the employer’s site.</div>`:'';return (availability.reason?`<div class="notice warn" style="margin-top:12px"><b>${esc(availability.label)}:</b> ${esc(availability.reason)}</div>`:'')+fetched}

function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function getJobById(id){return jobsData.find(x=>x.id===id)||state.apps.find(a=>a.jobId===id)?.jobSnapshot||seedJobs.find(x=>x.id===id)}
function openApp(){document.getElementById('landing').classList.add('hidden');document.getElementById('workspace').classList.remove('hidden');renderNav();showPage(state.page||'dashboard');loadLiveJobs()}
function goHome(){document.getElementById('workspace').classList.add('hidden');document.getElementById('landing').classList.remove('hidden');window.scrollTo(0,0)}
const pages=[['dashboard','Overview','▦'],['jobs','Discover','◎'],['applications','Applications','▣'],['profile','Profile','◉']];
function renderNav(){document.getElementById('nav').innerHTML=pages.map(([id,label,icon])=>`<button data-page="${id}" onclick="showPage('${id}')">${icon}&nbsp;&nbsp;${label}</button>`).join('')+`<button onclick="goHome()">←&nbsp;&nbsp;Landing page</button>`}
function showPage(id){internActiveView=id;state.page=id;persist();document.querySelectorAll('.side-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));({dashboard,jobs,applications,profile}[id]||dashboard)();if((id==='dashboard'||id==='jobs')&&!jobsLoaded)loadLiveJobs()}

const internDiagnostics=[],internReportedCodes=new Set();
function diagnosticsSharingEnabled(){try{return localStorage.getItem('internai-share-diagnostics')==='true'}catch{return false}}
function setDiagnosticsSharing(enabled){try{localStorage.setItem('internai-share-diagnostics',String(!!enabled))}catch{toast('Could not save this preference.')}}
function sendDiagnostic(code){
 if(!diagnosticsSharingEnabled()||location.protocol!=='https:'||internReportedCodes.has(code))return;
 internReportedCodes.add(code);
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4000);
 try{Promise.resolve(fetch('/api/diagnostics',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'omit',referrerPolicy:'no-referrer',body:JSON.stringify({code,version:INTERN_STATE_VERSION}),signal:controller.signal})).catch(()=>{}).finally(()=>clearTimeout(timer))}catch{clearTimeout(timer)}
}

function recordDiagnostic(code){const allowed=['local_save_failed','cloud_read_failed','cloud_write_failed','feed_partial','script_error','unhandled_rejection','download_failed'];if(!allowed.includes(code))return;internDiagnostics.push({code,at:new Date().toISOString()});if(internDiagnostics.length>30)internDiagnostics.shift();sendDiagnostic(code)}
function diagnosticsText(){return JSON.stringify({version:INTERN_STATE_VERSION,events:internDiagnostics,feeds:typeof feedStatus==='undefined'?null:feedStatus.sources.map(s=>({source:s.label,ok:s.ok,partial:s.partial,count:s.count})),sync:typeof syncLabel==='function'?syncLabel():''},null,2)}
async function copyDiagnostics(){try{await navigator.clipboard.writeText(diagnosticsText());toast('Diagnostics copied. No profile or resume contents included.')}catch{toast('Could not copy diagnostics. Try again in a supported browser.')}}
let internDownloadCleanup=null;
function downloadTextFile(text,filename,mime='text/plain;charset=utf-8'){
 if(internDownloadCleanup)internDownloadCleanup();
 const panel=document.createElement('aside'),previousFocus=document.activeElement;
 panel.id='intern-download';panel.className='download-panel';panel.setAttribute('aria-label','File download');
 panel.innerHTML='<p role="status"></p><div class="row"><a class="btn outline">Download again</a><button type="button" class="btn outline">Copy contents</button><button type="button" class="btn outline">Close</button></div><textarea hidden readonly aria-label="File contents for manual copy"></textarea>';
 const status=panel.querySelector('[role="status"]'),link=panel.querySelector('a'),buttons=panel.querySelectorAll('button'),manual=panel.querySelector('textarea');let url=null;
 const cleanup=()=>{panel.remove();if(url){const old=url;setTimeout(()=>URL.revokeObjectURL(old),60000);url=null}if(internDownloadCleanup===cleanup)internDownloadCleanup=null};
 internDownloadCleanup=cleanup;
 const close=()=>{const focused=panel.contains(document.activeElement);cleanup();if(focused&&previousFocus?.isConnected)previousFocus.focus()};
 buttons[1].onclick=close;panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.stopPropagation();close()}});
 buttons[0].onclick=async()=>{try{await navigator.clipboard.writeText(text);status.textContent='Contents copied.'}catch{manual.hidden=false;manual.value=text;manual.focus();manual.select();status.textContent='Select and copy the contents below.'}};
 const activeDialog=document.querySelector('dialog[open]');
 if(activeDialog){panel.style.position='static';panel.style.width='100%';panel.style.marginTop='12px';activeDialog.appendChild(panel);activeDialog.addEventListener('close',cleanup,{once:true})}else document.body.appendChild(panel);
 try{url=URL.createObjectURL(new Blob([text],{type:mime}));link.href=url;link.download=filename;status.textContent='Download requested. Check your downloads; if no file appears, try again or copy the contents.';link.click();return true}
 catch{link.hidden=true;status.textContent='Could not start the download. Copy the contents instead.';recordDiagnostic('download_failed');return false}
}
function exportWorkspaceBackup(){return downloadTextFile(JSON.stringify({format:'internai-workspace',exportedAt:new Date().toISOString(),workspace:state},null,2),'internai-workspace-backup.json','application/json')}
window.addEventListener('error',()=>recordDiagnostic('script_error'));
window.addEventListener('unhandledrejection',()=>recordDiagnostic('unhandled_rejection'));

const listingChecksInFlight=new Set();
async function checkListingStatus(id){const job=getJobById(id);if(!job||listingChecksInFlight.has(id))return;const profile=state.profile;listingChecksInFlight.add(id);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);toast('Checking employer posting…');try{const r=await fetch('/api/listing-status?url='+encodeURIComponent(job.applyUrl||''),{signal:controller.signal});if(!r.ok)throw new Error('Unavailable');const check=await r.json();if(state.profile!==profile)return;if(!['open','unavailable','unknown'].includes(check.status))throw new Error('Invalid response');job.availabilityCheck={status:check.status,checkedAt:check.checkedAt||new Date().toISOString()};for(const app of state.apps)if(app.jobId===id&&app.jobSnapshot)app.jobSnapshot.availabilityCheck=job.availabilityCheck;persist();toast(check.status==='open'?'Provider currently lists this posting':check.status==='unavailable'?'Posting unavailable — it may have closed or moved':'Could not verify automatically. Check the employer page.');if(internActiveView==='openJob'&&internActiveJobId===id)openJob(id)}catch{toast('Could not verify this posting. Check the employer page.')}finally{clearTimeout(timer);listingChecksInFlight.delete(id)}}
