const {test,expect}=require('@playwright/test');
const job={id:'qa-role',company:'QA Employer',title:'Mechanical Engineering Intern',location:'Cleveland, OH',mode:'On-site',season:['Summer'],year:2027,live:true,source:'QA feed',applyUrl:'https://example.com/job',skills:['CAD'],desc:'Required Qualifications\nPursuing Mechanical Engineering\nKnowledge of CAD'};
test.beforeEach(async({page})=>{
 // No production account, employer submission, email or paid service is touched.
 await page.route('https://**/*',route=>route.abort());
 await page.route('**/api/**',route=>route.fulfill({json:{jobs:route.request().url().includes('midwest')?[]:[job],updatedAt:'2026-09-21T00:00:00Z'}}));
});
async function downloadedText(download){const stream=await download.createReadStream(),chunks=[];for await(const chunk of stream)chunks.push(chunk);return Buffer.concat(chunks).toString('utf8')}
async function openWorkspace(page){await page.goto('/');await page.locator('.hero-buttons').getByRole('button',{name:'Build your profile →',exact:true}).click();await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible()}
test('landing and workspace fit the viewport without horizontal overflow',async({page})=>{await page.goto('/');await expect(page.locator('#how .feature')).toHaveCount(3);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.hero-buttons').getByRole('button',{name:'Build your profile →',exact:true}).click();await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
test('import, edit, download, track, reload keeps user materials',async({page})=>{
 await openWorkspace(page);await page.locator('[data-page="jobs"]').click();await expect(page.getByText(/Last refresh:/)).toBeVisible();await page.getByRole('button',{name:'Add a job you found',exact:true}).click();
 await page.locator('#importUrl').fill('https://example.com/job');await page.locator('#importTitle').fill('QA Mechanical Intern');await page.locator('#importCompany').fill('QA Company');await page.locator('#importDesc').fill('Summer 2027 mechanical engineering internship. CAD experience required.');await page.getByRole('button',{name:'Analyze & create workspace →',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Application Workspace',exact:true})).toBeVisible();await page.getByRole('button',{name:'Tailor my resume',exact:true}).click();await page.locator('#tailoredResumeDraft').fill('QA reviewed source material');
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-resume-view="tailored"]').getByRole('button',{name:'Download text',exact:true}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe('tailored-resume.txt');expect(await downloadedText(download)).toBe('QA reviewed source material');await expect(page.locator('#intern-download')).toContainText('Download requested');const retry=page.waitForEvent('download');await page.locator('#intern-download').getByRole('link',{name:'Download again'}).click();expect(await downloadedText(await retry)).toBe('QA reviewed source material');await page.locator('#intern-download').getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Continue to application →',exact:true}).click();await expect(page.getByRole('button',{name:'Open application site ↗',exact:true})).toBeVisible();await page.getByRole('button',{name:'I submitted it ✓',exact:true}).click();await expect(page.locator('#astatus')).toHaveValue('Applied');
 await page.reload();await page.locator('.hero-buttons').getByRole('button',{name:'Build your profile →',exact:true}).click();await page.locator('[data-page="applications"]').click();await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.locator('#tailoredResumeDraft')).toHaveValue('QA reviewed source material');
});
test('workspace deep link starts after all scripts load',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#app');await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();expect(errors).toEqual([])});
test('listing verification displays removal without erasing application work',async({page})=>{
 await page.route('**/api/listing-status?*',route=>route.fulfill({json:{status:'unavailable',checkedAt:new Date().toISOString()}}));
 await openWorkspace(page);await page.locator('[data-page="jobs"]').click();await expect(page.getByText(/Last refresh:/)).toBeVisible();
 await page.getByRole('button',{name:'Add a job you found',exact:true}).click();await page.locator('#importUrl').fill('https://job-boards.greenhouse.io/example/jobs/123');await page.locator('#importTitle').fill('QA Intern');await page.locator('#importCompany').fill('QA Company');await page.getByRole('button',{name:'Analyze & create workspace →',exact:true}).click();
 await page.getByRole('button',{name:'← Match details',exact:true}).click();await page.getByRole('button',{name:'Check availability',exact:true}).click();await expect(page.getByText('Posting unavailable:',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Employer listing ↗',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Open Application Workspace →',exact:true})).toBeVisible();
});

test('cloud conflict keeps local edits and requires backup before restoring cloud',async({page})=>{
 await page.route('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2',route=>route.fulfill({contentType:'application/javascript',body:`window.supabase={createClient:()=>({auth:{onAuthStateChange(){},async getSession(){return{data:{session:{user:{id:'qa-user',email:'qa@example.invalid'}}}}}},from(table){return{select(){return this},eq(){return this},async maybeSingle(){return{data:table==='profiles'?{name:'Cloud version',updated_at:'2026-09-22T00:00:00+00:00'}:{saved:[],applications:[],updated_at:'2026-09-22T00:00:00+00:00'},error:null}}}},async rpc(){return{error:{code:'PT409'}}}})};`}));
 await openWorkspace(page);await expect(page.locator('#account-controls')).toContainText('Synced');await page.locator('[data-page="profile"]').click();await page.locator('#pname').fill('Local device edit');
 await expect(page.locator('#account-controls')).toContainText('Cloud conflict');await expect(page.locator('#pname')).toHaveValue('Local device edit');await page.getByRole('button',{name:'Resolve sync conflict',exact:true}).click();
 const dialog=page.locator('#intern-conflict-dialog');await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Load cloud version',exact:true})).toBeDisabled();
 const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download local backup',exact:true}).click();expect((await download).suggestedFilename()).toBe('internai-workspace-backup.json');
 await dialog.getByRole('button',{name:'Load cloud version',exact:true}).click();await expect(page.locator('#pname')).toHaveValue('Cloud version');await expect(page.locator('#account-controls')).toContainText('Synced');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('backup restore previews replacement and keeps notes after reload',async({page})=>{
 await openWorkspace(page);await page.locator('[data-page="profile"]').click();await page.locator('#pname').fill('Current profile');
 const backup={format:'internai-workspace',workspace:{version:2,profile:{name:'Recovered profile',skills:['CAD'],resumeText:''},saved:[],apps:[{id:'recovered-app',company:'Recovery employer',title:'Recovered internship',status:'Applied',notes:'Preserved application notes',draft:'Reviewed cover letter'}]}};
 await page.locator('#workspaceBackupFile').setInputFiles({name:'workspace.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
 const dialog=page.locator('#intern-backup-dialog');await expect(dialog).toBeVisible();await expect(dialog).toContainText('1 applications');await expect(dialog.getByRole('button',{name:'Replace with backup',exact:true})).toBeDisabled();await expect(page.locator('#pname')).toHaveValue('Current profile');
 const downloaded=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download current workspace',exact:true}).click();const backupFile=await downloaded;expect(backupFile.suggestedFilename()).toBe('internai-workspace-backup.json');const contents=JSON.parse(await downloadedText(backupFile));expect(contents.format).toBe('internai-workspace');expect(contents.workspace.profile.name).toBe('Current profile');await dialog.getByRole('button',{name:'Replace with backup',exact:true}).click();await expect(page.locator('#pname')).toHaveValue('Recovered profile');
 await page.reload();await page.locator('.hero-buttons').getByRole('button',{name:'Build your profile →',exact:true}).click();await page.locator('[data-page="applications"]').click();await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.locator('#anotes')).toHaveValue('Preserved application notes');await expect(page.locator('#adraft')).toHaveValue('Reviewed cover letter');
});
test('tracking notes autosave, status history appears, and cleared drafts stay cleared',async({page})=>{
 await openWorkspace(page);await page.locator('[data-page="jobs"]').click();await page.getByRole('button',{name:'Add a job you found',exact:true}).click();await page.locator('#importUrl').fill('https://example.com/tracking');await page.locator('#importTitle').fill('Tracking QA intern');await page.locator('#importCompany').fill('Tracking QA');await page.getByRole('button',{name:'Analyze & create workspace →',exact:true}).click();
 await page.getByRole('button',{name:'Tracking & notes',exact:true}).click();await page.locator('#anotes').fill('Ask about interview availability Friday.');await page.locator('#astatus').selectOption('Interview');await expect(page.locator('#applicationStatusHistory')).toContainText('Interview');await page.locator('#adraft').fill('');await expect(page.locator('#applicationSaveState')).toHaveText('Saved locally');
 await page.reload();await page.locator('.hero-buttons').getByRole('button',{name:'Build your profile →',exact:true}).click();await page.locator('[data-page="applications"]').click();await page.getByRole('button',{name:'Open',exact:true}).click();await page.getByRole('button',{name:'Tracking & notes',exact:true}).click();await expect(page.locator('#anotes')).toHaveValue('Ask about interview availability Friday.');await expect(page.locator('#astatus')).toHaveValue('Interview');await expect(page.locator('#applicationStatusHistory')).toContainText('Interview');await expect(page.locator('#adraft')).toHaveValue('');
 page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'Regenerate from profile',exact:true}).click();await expect(page.locator('#adraft')).toHaveValue('');
});

test('blocked download and clipboard expose manual copy, with keyboard dismissal',async({page})=>{
 await openWorkspace(page);await page.locator('[data-page="profile"]').click();await page.getByLabel('Full name',{exact:true}).fill('Download fallback QA');
 await page.evaluate(()=>{URL.createObjectURL=()=>{throw Error('Blocked')};Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('Denied')}},configurable:true})});
 await page.getByRole('button',{name:'Download workspace backup',exact:true}).click();const panel=page.locator('#intern-download');await expect(panel).toContainText('Could not start the download');await panel.getByRole('button',{name:'Copy contents',exact:true}).click();const contents=panel.getByRole('textbox',{name:'File contents for manual copy'});await expect(contents).toBeVisible();expect(JSON.parse(await contents.inputValue()).workspace.profile.name).toBe('Download fallback QA');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await contents.press('Escape');await expect(panel).toHaveCount(0);
});

test('discovery area, term and link controls narrow and broaden actual results',async({page})=>{
 const fixtures=[{...job,id:'local',company:'Solon employer',location:'Solon, OH'},{...job,id:'state',company:'Columbus employer',location:'Columbus, OH'},{...job,id:'unknown',company:'Unlisted term employer',location:'Solon, OH',season:['Unspecified'],year:null},{...job,id:'missing',company:'Missing link employer',location:'Solon, OH',applyUrl:''}];
 await page.route('**/api/**',route=>route.fulfill({json:{jobs:route.request().url().includes('midwest')?[]:fixtures.map((j,i)=>({...j,applyUrl:j.applyUrl?`https://example.com/role-${i}`:''}))}}));
 await openWorkspace(page);await page.locator('[data-page="profile"]').click();await page.locator('#plocation').fill('Mayfield Village, OH');await page.locator('#pworkPreference').selectOption('close-home');await page.locator('[data-page="jobs"]').click();await expect(page.getByText(/Last refresh:/)).toBeVisible();
 const results=page.locator('#page > .jobs');await expect(results).toContainText('Solon employer');await expect(results).not.toContainText('Columbus employer');await expect(results).not.toContainText('Unlisted term employer');
 await page.getByLabel('Search area',{exact:true}).selectOption('state');await expect(results).toContainText('Columbus employer');await page.getByLabel('Include unlisted terms',{exact:true}).check();await expect(results).toContainText('Unlisted term employer');await page.getByLabel('Application links only',{exact:true}).check();await expect(results).not.toContainText('Missing link employer');
 await page.getByLabel('Specific location (optional)',{exact:true}).fill('Cleveland, TN');await page.getByRole('button',{name:'Apply overrides',exact:true}).click();await expect(results).toContainText('No roles match');await page.getByRole('button',{name:'Reset to profile',exact:true}).click();await expect(page.getByLabel('Specific location (optional)',{exact:true})).toHaveValue('');await expect(results).toContainText('Solon employer');await expect(results).not.toContainText('Columbus employer');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('scheduled tasks and interview preparation survive reload and completed follow-ups disappear',async({page})=>{
 await openWorkspace(page);await page.locator('[data-page="jobs"]').click();await page.getByRole('button',{name:'Add a job you found',exact:true}).click();await page.locator('#importUrl').fill('https://example.com/schedule');await page.locator('#importTitle').fill('Schedule test intern');await page.locator('#importCompany').fill('Schedule employer');await page.getByRole('button',{name:'Analyze & create workspace →',exact:true}).click();await page.getByRole('button',{name:'Tracking & notes',exact:true}).click();
 const today=await page.evaluate(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`});
 await page.getByLabel('Application deadline',{exact:true}).fill(today);await page.getByLabel('Follow-up date',{exact:true}).fill(today);await page.getByLabel('Interview date',{exact:true}).fill(today);await page.getByLabel('Interview preparation & details',{exact:true}).fill('10 AM Eastern. Ask about manufacturing projects.');await page.locator('[data-page="dashboard"]').click();const agenda=page.getByRole('region',{name:'Needs your attention'});await expect(agenda).toContainText('Schedule employer');await expect(agenda.getByRole('button',{name:'Review task',exact:true})).toHaveCount(3);
 await page.reload();await page.locator('.hero-buttons').getByRole('button',{name:'Build your profile →',exact:true}).click();await page.getByRole('region',{name:'Needs your attention'}).getByRole('button',{name:'Review task',exact:true}).first().click();await expect(page.getByLabel('Interview preparation & details',{exact:true})).toHaveValue('10 AM Eastern. Ask about manufacturing projects.');await expect(page.getByLabel('Interview date',{exact:true})).toHaveValue(today);await page.getByRole('button',{name:'Mark follow-up done',exact:true}).click();await expect(page.getByLabel('Follow-up date',{exact:true})).toHaveValue('');await page.getByLabel('Status',{exact:true}).selectOption('Applied');await page.locator('[data-page="applications"]').click();const tasks=page.getByRole('region',{name:'Needs your attention'});await expect(tasks.getByRole('button',{name:'Review task',exact:true})).toHaveCount(1);await expect(tasks).toContainText('Interview');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
