const {test,expect}=require('@playwright/test');
const job={id:'qa-role',company:'QA Employer',title:'Mechanical Engineering Intern',location:'Cleveland, OH',mode:'On-site',season:['Summer'],year:2027,live:true,source:'QA feed',applyUrl:'https://example.com/job',skills:['CAD'],desc:'Required Qualifications\nPursuing Mechanical Engineering\nKnowledge of CAD'};
test.beforeEach(async({page})=>{
 // No production account, employer submission, email or paid service is touched.
 await page.route('https://**/*',route=>route.abort());
 await page.route('**/api/**',route=>route.fulfill({json:{jobs:route.request().url().includes('midwest')?[]:[job],updatedAt:'2026-09-21T00:00:00Z'}}));
});
async function openWorkspace(page){await page.goto('/');await page.getByRole('button',{name:'Start free →',exact:true}).click();await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible()}
test('landing and workspace fit the viewport without horizontal overflow',async({page})=>{await page.goto('/');await expect(page.locator('#how .feature')).toHaveCount(3);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Start free →',exact:true}).click();await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)});
test('import, edit, download, track, reload keeps user materials',async({page})=>{
 await openWorkspace(page);await page.locator('[data-page="jobs"]').click();await expect(page.getByText(/Last refresh:/)).toBeVisible();await page.getByRole('button',{name:'Add a job you found',exact:true}).click();
 await page.locator('#importUrl').fill('https://example.com/job');await page.locator('#importTitle').fill('QA Mechanical Intern');await page.locator('#importCompany').fill('QA Company');await page.locator('#importDesc').fill('Summer 2027 mechanical engineering internship. CAD experience required.');await page.getByRole('button',{name:'Analyze & create workspace →',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Application Workspace',exact:true})).toBeVisible();await page.getByRole('button',{name:'Tailor my resume',exact:true}).click();await page.locator('#tailoredResumeDraft').fill('QA reviewed source material');
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-resume-view="tailored"]').getByRole('button',{name:'Download text',exact:true}).click();const download=await downloadPromise;expect(download.suggestedFilename()).toBe('tailored-resume.txt');
 await page.getByRole('button',{name:'Continue to application →',exact:true}).click();await expect(page.getByRole('button',{name:'Open application site ↗',exact:true})).toBeVisible();await page.getByRole('button',{name:'I submitted it ✓',exact:true}).click();await expect(page.locator('#astatus')).toHaveValue('Applied');
 await page.reload();await page.getByRole('button',{name:'Start free →',exact:true}).click();await page.locator('[data-page="applications"]').click();await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.locator('#tailoredResumeDraft')).toHaveValue('QA reviewed source material');
});
test('workspace deep link starts after all scripts load',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/#app');await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();expect(errors).toEqual([])});
test('listing verification displays removal without erasing application work',async({page})=>{
 await page.route('**/api/listing-status?*',route=>route.fulfill({json:{status:'unavailable',checkedAt:new Date().toISOString()}}));
 await openWorkspace(page);await page.locator('[data-page="jobs"]').click();await expect(page.getByText(/Last refresh:/)).toBeVisible();
 await page.getByRole('button',{name:'Add a job you found',exact:true}).click();await page.locator('#importUrl').fill('https://job-boards.greenhouse.io/example/jobs/123');await page.locator('#importTitle').fill('QA Intern');await page.locator('#importCompany').fill('QA Company');await page.getByRole('button',{name:'Analyze & create workspace →',exact:true}).click();
 await page.getByRole('button',{name:'← Match details',exact:true}).click();await page.getByRole('button',{name:'Check availability',exact:true}).click();await expect(page.getByText('Posting unavailable:',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Employer listing ↗',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Open Application Workspace →',exact:true})).toBeVisible();
});

test('cloud conflict keeps local edits and requires backup before restoring cloud',async({page})=>{
 await page.route('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2',route=>route.fulfill({contentType:'application/javascript',body:`window.supabase={createClient:()=>({auth:{onAuthStateChange(){},async getSession(){return{data:{session:{user:{id:'qa-user',email:'qa@example.invalid'}}}}}},from(table){return{select(){return this},eq(){return this},async maybeSingle(){return{data:table==='profiles'?{name:'Cloud version',updated_at:'2026-09-22T00:00:00+00:00'}:{saved:[],applications:[],updated_at:'2026-09-22T00:00:00+00:00'},error:null}}}},async rpc(){return{error:{code:'PT409'}}}})};`}));
 await openWorkspace(page);await expect(page.locator('#account-controls')).toContainText('Synced');await page.locator('[data-page="profile"]').click();await page.locator('#pname').fill('Local device edit');
 await expect(page.locator('#account-controls')).toContainText('Cloud conflict');await expect(page.locator('#pname')).toHaveValue('Local device edit');await page.getByRole('button',{name:'Resolve sync conflict',exact:true}).click();
 const dialog=page.locator('#intern-conflict-dialog');await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Load cloud version',exact:true})).toBeDisabled();
 const download=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download local backup',exact:true}).click();expect((await download).suggestedFilename()).toBe('internai-workspace-backup.json');
 await dialog.getByRole('button',{name:'Load cloud version',exact:true}).click();await expect(page.locator('#pname')).toHaveValue('Cloud version');await expect(page.locator('#account-controls')).toContainText('Synced');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('backup restore previews replacement and keeps notes after reload',async({page})=>{
 await openWorkspace(page);await page.locator('[data-page="profile"]').click();await page.locator('#pname').fill('Current profile');
 const backup={format:'internai-workspace',workspace:{version:2,profile:{name:'Recovered profile',skills:['CAD'],resumeText:''},saved:[],apps:[{id:'recovered-app',company:'Recovery employer',title:'Recovered internship',status:'Applied',notes:'Preserved application notes',draft:'Reviewed cover letter'}]}};
 await page.locator('#workspaceBackupFile').setInputFiles({name:'workspace.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});
 const dialog=page.locator('#intern-backup-dialog');await expect(dialog).toBeVisible();await expect(dialog).toContainText('1 applications');await expect(dialog.getByRole('button',{name:'Replace with backup',exact:true})).toBeDisabled();await expect(page.locator('#pname')).toHaveValue('Current profile');
 const downloaded=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download current workspace',exact:true}).click();expect((await downloaded).suggestedFilename()).toBe('internai-workspace-backup.json');await dialog.getByRole('button',{name:'Replace with backup',exact:true}).click();await expect(page.locator('#pname')).toHaveValue('Recovered profile');
 await page.reload();await page.getByRole('button',{name:'Start free →',exact:true}).click();await page.locator('[data-page="applications"]').click();await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.locator('#anotes')).toHaveValue('Preserved application notes');await expect(page.locator('#adraft')).toHaveValue('Reviewed cover letter');
});
