// Supabase persistence bridge v1 — keeps the existing local-first MVP working while adding authenticated cloud sync.
const INTERN_SUPABASE_URL='https://hoodrasmrhdzkjhmrorq.supabase.co';
const INTERN_SUPABASE_KEY='sb_publishable_m6WNadKQPbivmJORFEageA_qKioCJiV';
let internSupabase=null,internUser=null,internSyncTimer=null,internHydrating=false;
function supabaseReady(){return !!(window.supabase&&window.supabase.createClient)}
function profileRow(p={}){return{user_id:internUser.id,name:p.name||'',personal_email:p.personalEmail||'',school_email:p.schoolEmail||'',school:p.school||'',major:p.major||'',grad:p.grad||'',gpa:p.gpa||'',location:p.location||'',work_preference:p.workPreference||'',summary:p.summary||'',skills:Array.isArray(p.skills)?p.skills:[],resume_text:p.resumeText||'',resume_filename:p.resumeFilename||'',evidence:Array.isArray(p.evidence)?p.evidence:[],updated_at:new Date().toISOString()}}
function profileState(r={}){return{name:r.name||'',personalEmail:r.personal_email||'',schoolEmail:r.school_email||'',school:r.school||'',major:r.major||'',grad:r.grad||'',gpa:r.gpa||'',location:r.location||'',workPreference:r.work_preference||'',summary:r.summary||'',skills:r.skills||[],resumeText:r.resume_text||'',resumeFilename:r.resume_filename||'',evidence:r.evidence||[]}}
async function cloudPull(){if(!internUser||internHydrating)return;internHydrating=true;try{const [{data:p,error:pe},{data:s,error:se}]=await Promise.all([internSupabase.from('profiles').select('*').eq('user_id',internUser.id).maybeSingle(),internSupabase.from('user_state').select('*').eq('user_id',internUser.id).maybeSingle()]);if(pe)throw pe;if(se)throw se;const local=load(),cloudHasData=p&&(p.name||p.school||p.resume_text)||(s&&((s.saved||[]).length||(s.applications||[]).length));if(cloudHasData){state={...local,profile:{...local.profile,...profileState(p||{})},saved:s?.saved||[],apps:s?.applications||[]};localStorage.setItem('internai-demo',JSON.stringify(state));if(!document.getElementById('workspace').classList.contains('hidden'))showPage(state.page||'dashboard')}else await cloudPush()}catch(e){console.warn('InternAI cloud pull failed; local state preserved.',e)}finally{internHydrating=false}}
async function cloudPush(){if(!internUser||internHydrating)return;try{const p=profileRow(state.profile),s={user_id:internUser.id,saved:state.saved||[],applications:state.apps||[],updated_at:new Date().toISOString()};const [{error:pe},{error:se}]=await Promise.all([internSupabase.from('profiles').upsert(p),internSupabase.from('user_state').upsert(s)]);if(pe)throw pe;if(se)throw se}catch(e){console.warn('InternAI cloud sync failed; local state preserved.',e)}}
const localPersist=persist;persist=function(){localPersist();if(internUser){clearTimeout(internSyncTimer);internSyncTimer=setTimeout(cloudPush,350)}};
async function internSignIn(email,password){if(!internSupabase)return toast('Cloud account service is still loading');const {error}=await internSupabase.auth.signInWithPassword({email,password});if(error)return toast(error.message);toast('Signed in — syncing your workspace')}
async function internSignUp(email,password){if(!internSupabase)return toast('Cloud account service is still loading');const {error}=await internSupabase.auth.signUp({email,password});if(error)return toast(error.message);toast('Account created — check your email if confirmation is required')}
async function internSignOut(){if(!internSupabase)return;await internSupabase.auth.signOut();internUser=null;toast('Signed out — this browser copy is still available')}
function accountControls(){return internUser?`<div class="row"><span style="font-size:11px;color:#64706a">${esc(internUser.email||'Signed in')}</span><button class="btn outline small" onclick="internSignOut()">Sign out</button></div>`:`<button class="btn outline small" onclick="accountDialog()">Sign in</button>`}
function accountDialog(){const email=prompt('InternAI account email');if(!email)return;const password=prompt('Password (8+ characters)');if(!password)return;const create=confirm('OK = create a new account. Cancel = sign in to an existing account.');return create?internSignUp(email,password):internSignIn(email,password)}
function renderAccountControls(){const bar=document.querySelector('.appbar .row');if(!bar)return;let box=document.getElementById('account-controls');if(!box){box=document.createElement('span');box.id='account-controls';bar.prepend(box)}box.innerHTML=accountControls()}
async function initInternCloud(){if(!supabaseReady())return;internSupabase=window.supabase.createClient(INTERN_SUPABASE_URL,INTERN_SUPABASE_KEY);const {data}=await internSupabase.auth.getSession();internUser=data.session?.user||null;renderAccountControls();if(internUser)await cloudPull();internSupabase.auth.onAuthStateChange(async(_,session)=>{internUser=session?.user||null;renderAccountControls();if(internUser)setTimeout(cloudPull,0)})}
window.addEventListener('DOMContentLoaded',initInternCloud);
