const test=require('node:test'),assert=require('node:assert/strict');
const {runtime}=require('./runtime.cjs');
function setup(){const r=runtime(['app1.js','app19.js']),writes=[];let rows={profiles:null,user_state:null},failRead=false,failWrite=false,hold=null;
 r.ctx.client={from(table){return {select(){return this},eq(k,id){this.id=id;return this},async maybeSingle(){const snapshot=structuredClone(rows[table]);if(hold)await hold;return {data:snapshot,error:failRead?Error('offline'):null}},async upsert(row){writes.push(structuredClone(row));return{error:failWrite?Error('offline'):null}}}},auth:{async signOut(){return{error:null}}}};
 r.run('internSupabase=client');
 return {...r,writes,rows,setReadFailure(v){failRead=v},setWriteFailure(v){failWrite=v},setHold(v){hold=v},login:id=>r.run(`adoptInternUser({id:${JSON.stringify(id)}}); cloudPull()`)};
}
test('anonymous profile, resume, graph and applications migrate',async()=>{const r=setup();r.run("state.profile.name='Anonymous';state.profile.resumeText='Source';state.profile.careerGraph={claims:['source']};state.apps=[{id:'app',status:'Applied'}];persist()");await r.login('A');assert.equal(r.writes[0].name,'Anonymous');assert.equal(r.writes[0].career_graph.claims[0],'source');assert.equal(r.writes[1].applications[0].status,'Applied')});
test('skills-only cloud profile is not treated as empty',async()=>{const r=setup();r.rows.profiles={skills:['Python']};r.run("state.profile.name='Anonymous';persist()");await r.login('A');assert.equal(r.run('state.profile.skills[0]'),'Python');assert.equal(r.run('state.profile.name'),'');assert.equal(r.writes.length,0)});
test('A sign-out then empty B never receives A data; A recovery retained',async()=>{const r=setup();r.run("state.profile.name='A data';persist()");await r.login('A');await r.run('internSignOut()');assert.equal(r.run('state.profile.name'),'');await r.login('B');assert.equal(r.writes.at(-2).name,'');await r.run('internSignOut()');await r.login('A');assert.equal(r.run('state.profile.name'),'A data')});
test('failed B hydration cannot upload or display A data',async()=>{const r=setup();r.run("state.profile.name='A data';persist()");await r.login('A');r.setReadFailure(true);const before=r.writes.length;await r.login('B');r.run("state.profile.name='B edit';persist()");await r.run('cloudPush()');assert.equal(r.writes.length,before);assert.ok(r.storage.get('internai-workspace:A').includes('A data'))});
test('late A cloud response cannot hydrate B or relabel its owner',async()=>{const r=setup();let release;r.setHold(new Promise(resolve=>release=resolve));r.rows.profiles={name:'A cloud'};const a=r.login('A');r.rows.profiles={name:'B cloud'};const b=r.login('B');release();await Promise.all([a,b]);assert.equal(r.run('state.profile.name'),'B cloud');assert.equal(r.storage.get('internai-local-owner'),'B')});
test('failed sync stays pending; reload does not replace local edits with stale cloud',async()=>{const r=setup();await r.login('A');r.setWriteFailure(true);r.run("state.profile.name='Unsynced';persist()");await r.run('cloudPush()');assert.equal(r.storage.get('internai-sync-pending:A'),'true');r.rows.profiles={name:'Old cloud'};r.setWriteFailure(false);await r.run('cloudPull()');assert.equal(r.run('state.profile.name'),'Unsynced');assert.equal(r.writes.at(-2).name,'Unsynced')});
test('sign-out failure retains session and workspace',async()=>{const r=setup();await r.login('A');r.ctx.client.auth.signOut=async()=>({error:{message:'offline'}});await r.run('internSignOut()');assert.equal(r.run('internUser.id'),'A')});
test('same-user token refresh does not rehydrate over local state',async()=>{const r=setup();await r.login('A');assert.equal(r.run("adoptInternUser({id:'A'})"),false)});
test('edits during cloud restore are preserved without uploading over unknown cloud',async()=>{const r=setup();let release;r.setHold(new Promise(resolve=>release=resolve));r.rows.profiles={name:'Cloud'};const pull=r.login('A');r.run("state.profile.name='Local edit';persist()");release();await pull;assert.equal(r.run('state.profile.name'),'Local edit');assert.equal(r.writes.length,0)});
test('page navigation does not mark cloud profile dirty before restore',async()=>{const r=setup();r.run("state.profile.name='Old local';persist()");await r.login('A');r.storage.delete('internai-sync-pending:A');r.rows.profiles={name:'New cloud'};r.run("state.page='profile';persist()");assert.equal(r.storage.get('internai-sync-pending:A'),undefined);await r.run('cloudPull()');assert.equal(r.run('state.profile.name'),'New cloud')});
