const test=require('node:test'),assert=require('node:assert/strict');
const {runtime}=require('./runtime.cjs');
function setup(){const r=runtime(['js/workspace.js','js/account-sync.js']),writes=[];let rows={},database={},version=0,failRead=false,failWrite=false,hold=null;
 r.ctx.client={from(table){return {select(){return this},eq(k,id){this.id=id;return this},async maybeSingle(){let snapshot=structuredClone(rows[table]===undefined?database[this.id]?.[table]||null:rows[table]);if(snapshot&&!snapshot.updated_at)snapshot.updated_at=database[this.id]?.[table]?.updated_at||null;if(hold)await hold;return {data:snapshot,error:failRead?Error('offline'):null}}}},async rpc(name,args){
  assert.equal(name,'save_intern_workspace');if(failWrite)return{error:Error('offline')};
  const id=r.run('internUser.id'),db=database[id]||{};
  const pv=rows.profiles?.updated_at||db.profiles?.updated_at||null,sv=rows.user_state?.updated_at||db.user_state?.updated_at||null;
  if(pv!==args.expected_profile||sv!==args.expected_state)return{error:{code:'PT409'}};
  const stamp=String(++version),profile={...structuredClone(args.profile_data),updated_at:stamp},state={user_id:id,saved:structuredClone(args.saved_data),applications:structuredClone(args.applications_data),updated_at:stamp};
  database[id]={profiles:profile,user_state:state};writes.push(profile,state);return{data:{profile:stamp,state:stamp},error:null};
 },auth:{async signOut(){return{error:null}}}};
 r.run('internSupabase=client');
 return {...r,writes,rows,setReadFailure(v){failRead=v},setWriteFailure(v){failWrite=v},setHold(v){hold=v},login:id=>r.run(`adoptInternUser({id:${JSON.stringify(id)}}); cloudPull()`)};
}
test('anonymous profile, resume, graph and applications migrate',async()=>{const r=setup();r.run("state.profile.name='Anonymous';state.profile.resumeText='Source';state.profile.careerGraph={claims:['source']};state.apps=[{id:'app',status:'Applied'}];persist()");await r.login('A');assert.equal(r.writes[0].name,'Anonymous');assert.equal(r.writes[0].career_graph.claims[0],'source');assert.equal(r.writes[1].applications[0].status,'Applied')});
test('skills-only cloud profile is not treated as empty',async()=>{const r=setup();r.rows.profiles={skills:['Python']};r.run("state.profile.name='Anonymous';persist()");await r.login('A');assert.equal(r.run('state.profile.skills[0]'),'Python');assert.equal(r.run('state.profile.name'),'');assert.equal(r.writes.length,0)});
test('A sign-out then empty B never receives A data; A recovery retained',async()=>{const r=setup();r.run("state.profile.name='A data';persist()");await r.login('A');await r.run('internSignOut()');assert.equal(r.run('state.profile.name'),'');await r.login('B');assert.equal(r.writes.at(-2).name,'');await r.run('internSignOut()');await r.login('A');assert.equal(r.run('state.profile.name'),'A data')});
test('failed B hydration cannot upload or display A data',async()=>{const r=setup();r.run("state.profile.name='A data';persist()");await r.login('A');r.setReadFailure(true);const before=r.writes.length;await r.login('B');r.run("state.profile.name='B edit';persist()");await r.run('cloudPush()');assert.equal(r.writes.length,before);assert.ok(r.storage.get('internai-workspace:A').includes('A data'))});
test('late A cloud response cannot hydrate B or relabel its owner',async()=>{const r=setup();let release;r.setHold(new Promise(resolve=>release=resolve));r.rows.profiles={name:'A cloud'};const a=r.login('A');r.rows.profiles={name:'B cloud'};const b=r.login('B');release();await Promise.all([a,b]);assert.equal(r.run('state.profile.name'),'B cloud');assert.equal(r.storage.get('internai-local-owner'),'B')});
test('failed sync stays pending; reload does not replace local edits with stale cloud',async()=>{const r=setup();await r.login('A');r.setWriteFailure(true);r.run("state.profile.name='Unsynced';persist()");await r.run('cloudPush()');assert.equal(r.storage.get('internai-sync-pending:A'),'true');r.rows.profiles={name:'Old cloud'};r.setWriteFailure(false);await r.run('cloudPull()');assert.equal(r.run('state.profile.name'),'Unsynced');assert.equal(r.writes.at(-2).name,'Unsynced')});
test('sign-out failure retains session and workspace',async()=>{const r=setup();await r.login('A');r.ctx.client.auth.signOut=async()=>({error:{message:'offline'}});await r.run('internSignOut()');assert.equal(r.run('internUser.id'),'A')});
test('same-user token refresh does not rehydrate over local state',async()=>{const r=setup();await r.login('A');assert.equal(r.run("adoptInternUser({id:'A'})"),false)});
test('edits during cloud restore are preserved without uploading over unknown cloud',async()=>{const r=setup();let release;r.setHold(new Promise(resolve=>release=resolve));r.rows.profiles={name:'Cloud'};const pull=r.login('A');r.run("state.profile.name='Local edit';persist()");release();await pull;assert.equal(r.run('state.profile.name'),'Local edit');assert.equal(r.writes.length,0)});
test('page navigation does not mark cloud profile dirty before restore',async()=>{const r=setup();r.run("state.profile.name='Old local';persist()");await r.login('A');r.storage.delete('internai-sync-pending:A');r.rows.profiles={name:'New cloud'};r.run("state.page='profile';persist()");assert.equal(r.storage.get('internai-sync-pending:A'),undefined);await r.run('cloudPull()');assert.equal(r.run('state.profile.name'),'New cloud')});
test('another tab changing shared owner cannot archive A under B',async()=>{const r=setup();r.run("state.profile.name='A private';persist()");await r.login('A');r.storage.set('internai-local-owner','B');r.storage.set('internai-demo',JSON.stringify({profile:{name:'B private'},apps:[],saved:[],page:'dashboard'}));r.setReadFailure(true);await r.login('B');assert.equal(r.run('state.profile.name'),'B private');assert.ok(r.storage.get('internai-workspace:A').includes('A private'));assert.equal(r.storage.get('internai-workspace:B'),undefined)});
test('cloud and account recovery use the workspace migration',async()=>{const r=setup();r.rows.profiles={name:'Legacy cloud'};r.rows.user_state={saved:[],applications:[{id:'old'}]};await r.login('A');assert.equal(r.run('state.apps[0].status'),'Interested');assert.equal(r.run('state.apps[0].statusHistory.length'),0);await r.run('internSignOut()');r.storage.set('internai-workspace:A',JSON.stringify({profile:{name:'Recovery'},apps:[{id:'recovered'}]}));r.setReadFailure(true);await r.login('A');assert.equal(r.run('state.version'),2);assert.equal(r.run('state.apps[0].status'),'Interested');assert.equal(r.run('state.profile.skills.length'),0)});
test('failed cloud restore refreshes the visible sync label',async()=>{const r=setup(),labels=[];r.ctx.labels=labels;r.run('renderAccountControls=()=>labels.push(syncLabel())');r.setReadFailure(true);await r.login('A');assert.ok(labels.includes(' · Restoring…'));assert.equal(labels.at(-1),' · Local only')});
test('password update survives currentTarget clearing after event dispatch and retries errors',async()=>{const r=setup();await r.login('A');const handlers={},button={disabled:false},form={elements:{password:{value:'synthetic-test-only'}},querySelector:()=>button,addEventListener:(type,fn)=>handlers[type]=fn};let closed=false,release;const dialog={style:{},addEventListener(){},querySelector:selector=>selector==='form'?form:{addEventListener(){}},showModal(){},close(){closed=true}};r.ctx.document.getElementById=id=>id==='toast'?{textContent:'',classList:{add(){},remove(){}}}:null;r.ctx.document.createElement=()=>dialog;r.ctx.document.body={appendChild(){}};r.ctx.client.auth.updateUser=()=>new Promise(resolve=>release=resolve);r.run('internPasswordUpdateDialog()');const event={preventDefault(){},currentTarget:form};const pending=handlers.submit(event);event.currentTarget=null;assert.equal(button.disabled,true);release({error:{message:'Try again'}});await pending;assert.equal(closed,false);assert.equal(form.elements.password.value,'');assert.equal(button.disabled,false);form.elements.password.value='synthetic-test-only';const retry=handlers.submit({preventDefault(){},currentTarget:form});release({error:null});await retry;assert.equal(closed,true);assert.equal(form.elements.password.value,'')});
test('signup and password reset send callbacks to the canonical deployed app',async()=>{const r=setup(),calls=[];r.ctx.location.origin='http://localhost:3000';r.ctx.client.auth.signUp=async input=>{calls.push(input.options.emailRedirectTo);return{error:null}};r.ctx.client.auth.resetPasswordForEmail=async(email,options)=>{calls.push(options.redirectTo);return{error:null}};await r.run("internSignUp('synthetic@example.test','synthetic-test-only')");await r.run("internRequestPasswordReset('synthetic@example.test')");assert.deepEqual(calls,['https://internai-mvp-fixed-devancalabrese-2065.vercel.app/','https://internai-mvp-fixed-devancalabrese-2065.vercel.app/'])});

test('same-account stale tab cannot overwrite another tab or push stale state',async()=>{const r=setup();await r.login('A');r.storage.set('internai-demo',JSON.stringify({profile:{name:'Newer tab'},apps:[],saved:[]}));const before=r.writes.length;r.run("state.profile.name='Older tab';persist()");await r.run('cloudPush()');assert.equal(JSON.parse(r.storage.get('internai-demo')).profile.name,'Newer tab');assert.equal(r.writes.length,before);assert.equal(r.run('internTabStale'),true)});
test('returning online retries pending changes',async()=>{const r=setup();await r.login('A');r.setWriteFailure(true);r.run("state.profile.name='Offline edit';persist()");await r.run('cloudPush()');r.setWriteFailure(false);await r.run('retryInternSync()');assert.equal(r.storage.get('internai-sync-pending:A'),undefined);assert.equal(r.writes.at(-2).name,'Offline edit')});
test('imported jobs restore from cloud application snapshots on a new device',async()=>{const r=setup();r.rows.profiles={name:'Cloud'};r.rows.user_state={saved:['imported'],applications:[{id:'a',jobId:'imported',jobSnapshot:{id:'imported',imported:true,applyUrl:'https://example.com/job'}}]};await r.login('A');assert.equal(r.run('state.importedJobs[0].id'),'imported')});
test('storage failure remains visible and keeps the current in-memory workspace',async()=>{const r=setup();await r.login('A');r.ctx.localStorage.setItem=()=>{throw Error('quota')};assert.equal(r.run("state.profile.name='Unsaved';persist()"),false);assert.match(r.run('syncLabel()'),/Not saved/);assert.equal(r.run('state.profile.name'),'Unsaved');assert.ok(r.run("internDiagnostics.some(e=>e.code==='local_save_failed')"))});

test('a newer device blocks stale upload and preserves local pending work',async()=>{const r=setup();await r.login('A');r.run("state.profile.name='Local edit';persist()");r.rows.profiles={name:'Newer device',updated_at:'remote-new'};const before=r.writes.length;await r.run('cloudPush()');assert.equal(r.writes.length,before);assert.equal(r.run('internCloudConflict'),true);assert.equal(r.run('state.profile.name'),'Local edit');assert.equal(r.storage.get('internai-sync-pending:A'),'true');assert.match(r.run('syncLabel()'),/conflict/);await r.run('cloudPush()');assert.equal(r.writes.length,before)});
test('pending edits after reload cannot adopt a newer baseline and overwrite cloud',async()=>{const r=setup();await r.login('A');r.run("state.profile.name='Offline edit';persist()");r.rows.user_state={saved:[],applications:[],updated_at:'new-device'};const before=r.writes.length;await r.run('cloudPull()');assert.equal(r.run('internCloudConflict'),true);assert.equal(r.run('state.profile.name'),'Offline edit');assert.equal(r.writes.length,before)});
test('legacy pending work with unknown baseline is preserved for explicit recovery',async()=>{const r=setup();await r.login('A');r.run("state.profile.name='Legacy local';persist()");r.storage.delete('internai-cloud-version:A');const before=r.writes.length;await r.run('cloudPull()');assert.equal(r.run('internCloudConflict'),true);assert.equal(r.writes.length,before)});
test('late save acknowledgement cannot change another account baseline',async()=>{const r=setup();await r.login('A');let release;r.ctx.client.rpc=()=>new Promise(resolve=>release=resolve);r.run("state.profile.name='A edit';persist()");const push=r.run('cloudPush()');r.run("adoptInternUser({id:'B'})");release({data:{profile:'A-new',state:'A-new'},error:null});await push;assert.equal(r.run('internCloudVersion'),null);assert.equal(r.storage.get('internai-cloud-version:B'),undefined)});
