const test=require('node:test'),assert=require('node:assert/strict'),{runtime}=require('./runtime.cjs');
function setup(){const r=runtime();r.run("state.profile=calibrationProfile({location:'Mayfield Village, OH',workPreference:'close-home'});jobsData=[]");return r}
test('metro locality is consistent between discovery and scoring, without treating all Ohio as local',()=>{const r=setup();for(const [location,relation] of [['Solon, OH','metro'],['Mentor, Ohio','metro'],['Columbus, OH','state'],['Cleveland, TN','other'],['Solon','unknown']]){r.ctx.job={location,mode:'On-site'};assert.equal(r.run('locationRelation(job)'),relation);assert.equal(r.run('calibratedLocationFit(job)'),r.run('locationTier(job)'));assert.equal(r.run('discoveryLocationFits(job)'),relation==='metro')}});
test('city matching respects word boundaries and state-qualified overrides',()=>{const r=setup();r.run("jobFilters.location='Cleveland, OH'");r.ctx.job={location:'Cleveland, TN'};assert.equal(r.run('discoveryLocationFits(job)'),false);r.ctx.job={location:'Cleveland, Ohio'};assert.equal(r.run('discoveryLocationFits(job)'),true);assert.equal(r.run("locationContains('Independence, OH','Erie')"),false)});
test('state and anywhere scopes broaden a close-home profile without changing it',()=>{const r=setup();r.ctx.job={location:'Columbus, OH',mode:'On-site'};r.run("jobFilters.area='state'");assert.equal(r.run('discoveryLocationFits(job)'),true);r.ctx.job.location='Pittsburgh, PA';assert.equal(r.run('discoveryLocationFits(job)'),false);r.run("jobFilters.area='any'");assert.equal(r.run('discoveryLocationFits(job)'),true);assert.equal(r.run('state.profile.workPreference'),'close-home')});
test('remote roles remain eligible for profile preference but do not pretend to be local',()=>{const r=setup();r.ctx.job={location:'United States',mode:'Remote'};assert.equal(r.run('discoveryLocationFits(job)'),true);assert.equal(r.run('locationTier(job)'),.72);r.run("jobFilters.area='metro'");assert.equal(r.run('discoveryLocationFits(job)'),false)});
test('unknown terms are optional and never let explicit wrong years into a selected season',()=>{const r=setup();r.run("jobFilters.area='any';jobsData=[calibrationJob({id:'summer',year:2027,season:['Summer']}),calibrationJob({id:'unknown',year:null,season:['Unspecified']}),calibrationJob({id:'old',year:2026,season:['Unspecified']}),calibrationJob({id:'fall',year:2027,season:['Fall']})]");assert.equal(r.run("filteredJobs().map(j=>j.id).join(',')"),'summer');r.run('jobFilters.includeUnknown=true');assert.equal(r.run("filteredJobs().map(j=>j.id).join(',')"),'summer,unknown');r.run("jobFilters.semester='all'");assert.equal(r.run('filteredJobs().length'),4)});
test('application-link filter hides samples, unsafe links and closed roles without removing saved work',()=>{const r=setup();r.run("jobFilters.area='any';jobFilters.actionable=true;state.saved=['closed'];jobsData=['open','closed','missing','sample'].map(id=>calibrationJob({id,live:id!=='sample',year:2027,season:['Summer'],applyUrl:id==='missing'?'javascript:alert(1)':'https://example.com/'+id,closed:id==='closed'}))");assert.equal(r.run("filteredJobs().map(j=>j.id).join(',')"),'open');assert.equal(r.run('state.saved[0]'),'closed');r.run('jobFilters.actionable=false');assert.equal(r.run('filteredJobs().length'),4)});
test('cards show unsupported required skills and unknown eligibility, with escaped employer text',()=>{const r=setup();const html=r.run("discoveryReviewNotes(calibrationJob({skills:[],degreeFields:[],year:null,season:['Unspecified'],desc:'Required Qualifications\\nExperience with GD&T\\nMust hold a security clearance <b>secret</b>'}))");assert.match(html,/Not supported by your profile/);assert.match(html,/Eligibility to review/);assert.match(html,/Target term is not confirmed/);assert.ok(!html.includes('<b>secret</b>'))});
