const test=require('node:test'),assert=require('node:assert/strict');
const {createLimiter}=require('../api/jobs-v2');
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(body){this.body=body;return this}}}
test('limiter includes slow response bodies and never exceeds six active requests',async()=>{let active=0,peak=0;const native=async()=>{active++;peak=Math.max(peak,active);return{status:200,statusText:'OK',headers:{},async arrayBuffer(){await pause(5);active--;return new TextEncoder().encode('{}')}}};const limiter=createLimiter(native,new AbortController().signal);await Promise.all(Array.from({length:24},()=>limiter('https://example.com')));assert.equal(peak,6);assert.equal(active,0)});
test('aborted queued work never starts an outbound request',async()=>{const c=new AbortController();let calls=0;const limited=createLimiter(async()=>{calls++;await pause(5);return new Response('{}')},c.signal,1);const first=limited('https://example.com');const second=limited('https://example.com');c.abort();await first;await assert.rejects(second,{name:'AbortError'});assert.equal(calls,1)});
test('two real handler invocations use isolated limiters and preserve global fetch',async()=>{const original=global.fetch;let active=0,peak=0;const fake=async(url)=>{active++;peak=Math.max(active,peak);await pause(2);active--;if(url.includes('lever.co'))return new Response(JSON.stringify([{id:'1',text:'Mechanical Engineering Intern Summer 2027',descriptionPlain:'CAD design',hostedUrl:url+'/job'}]));if(url.includes('greenhouse'))return new Response('{"jobs":[]}');if(url.includes('myworkdayjobs'))return new Response('{"jobPostings":[],"total":0}');return new Response('<html>no jobs</html>')};global.fetch=fake;try{const a=response(),b=response();await Promise.all([require('../api/jobs-v2')({method:'GET'},a),require('../api/jobs-v2')({method:'GET'},b)]);assert.equal(global.fetch,fake);assert.ok(peak<=12);assert.equal(a.body.count,5);assert.equal(b.body.count,5);assert.equal(a.statusCode,200)}finally{global.fetch=original}});
test('upstream failure returns usable partial JSON',async()=>{const {createHandler}=require('../api/jobs');const r=response();await createHandler(async()=>{throw Error('unavailable')})({method:'GET'},r);assert.equal(r.statusCode,200);assert.equal(r.body.partial,true);assert.equal(r.body.count,0);assert.ok(Array.isArray(r.body.jobs))});
test('health treats source degradation and malformed JSON honestly; ignores supplied host',async()=>{const original=global.fetch,host=process.env.VERCEL_URL,production=process.env.VERCEL_PROJECT_PRODUCTION_URL;delete process.env.VERCEL_PROJECT_PRODUCTION_URL;process.env.VERCEL_URL='internai-test.vercel.app';const seen=[];global.fetch=async url=>{seen.push(url);return new Response(JSON.stringify(url.endsWith('source-health')?{allHealthy:false,results:[{ok:false}]}:{jobs:[],count:0}))};try{const r=response();await require('../api/runtime-health')({method:'GET',headers:{host:'attacker.test','x-forwarded-host':'attacker.test'}},r);assert.equal(r.body.degraded,true);assert.ok(seen.every(x=>x.startsWith('https://internai-test.vercel.app/')));global.fetch=async()=>new Response('<html>Login</html>');const malformed=response();await require('../api/runtime-health')({method:'GET',headers:{}},malformed);assert.equal(malformed.statusCode,503);assert.ok(malformed.body.checks.every(x=>!x.ok))}finally{global.fetch=original;if(host===undefined)delete process.env.VERCEL_URL;else process.env.VERCEL_URL=host;if(production===undefined)delete process.env.VERCEL_PROJECT_PRODUCTION_URL;else process.env.VERCEL_PROJECT_PRODUCTION_URL=production}});
test('core excludes full-time roles despite internship mentions and decodes descriptions',async()=>{const {createHandler}=require('../api/jobs');const r=response();await createHandler(async url=>{if(url.includes('greenhouse'))return new Response(JSON.stringify({jobs:[{id:1,title:'Construction Superintendent',content:'Engineering team works with interns in summer 2027',absolute_url:'https://example.com/full-time'},{id:2,title:'Mechanical Engineering Intern Summer 2027',content:'&lt;p&gt;Design CAD parts.&lt;/p&gt;'+ ' Employer information.'.repeat(100)+' Minimum GPA 3.5.',absolute_url:'https://example.com/intern'}]}));if(url.includes('lever'))return new Response('[]');if(url.includes('workday'))return new Response('{"jobPostings":[],"total":0}');return new Response('<html></html>')})({method:'GET'},r);assert.equal(r.body.count,1);assert.equal(r.body.jobs[0].title,'Mechanical Engineering Intern Summer 2027');assert.ok(!r.body.jobs[0].desc.includes('<p>'));assert.ok(r.body.jobs[0].desc.includes('Minimum GPA 3.5.'))});
