const test=require('node:test'),assert=require('node:assert/strict');
const {runtime}=require('./runtime.cjs');
test('existing regression suite executes all eight cases',()=>{const r=runtime();assert.equal(r.ctx.window.internAIMatchRegressionResult.passed,true);assert.equal(r.ctx.window.internAIMatchRegressionResult.results.length,8)});
test('combined required skills do not credit missing GD&T',()=>{const r=runtime();const map=r.run("withCalibrationProfile(calibrationProfile({skills:['SolidWorks'],resumeText:''}),()=>structuredRequirementMap(calibrationJob({desc:'Required: SolidWorks and GD&T experience.'})))");assert.ok(map.some(x=>x.req.includes('GD&T')&&!x.supported))});
test('alternate accepted majors are recognized',()=>{const r=runtime();const map=r.run("withCalibrationProfile(calibrationProfile({major:'Electrical Engineering'}),()=>structuredRequirementMap(calibrationJob({degreeFields:['Mechanical','Electrical'],desc:'Required: pursuing a Mechanical or Electrical Engineering degree.'})))");assert.ok(map.some(x=>x.kind==='eligibility'&&x.supported))});
test('same-length job text change invalidates requirement cache',()=>{const r=runtime();assert.equal(r.run("(()=>{const j=calibrationJob({desc:'Minimum GPA 3.0.'});jobRequirementGraph(j);j.desc='Minimum GPA 3.8.';return jobRequirementGraph(j).nodes.some(x=>x.text.includes('3.8'))})()"),true)});
test('graduation eligibility is never credited from generic resume token overlap',()=>{const r=runtime();const map=r.run("withCalibrationProfile(calibrationProfile(),()=>structuredRequirementMap(calibrationJob({desc:'Must graduate in May 2028.'})))");assert.ok(map.some(x=>x.req.includes('2028')&&!x.supported&&!x.known))});
test('tailoring and provenance contain only exact source claims',()=>{const r=runtime();const result=r.run("withCalibrationProfile(calibrationProfile(),()=>{const j=calibrationJob(),plan=tailoringEvidencePlan(j);return {source:state.profile.resumeText,claims:plan.sections.flatMap(s=>s.claims),draft:tailoredResumeDraft(j),trace:tailoringProvenance(j)}})");assert.ok(result.claims.length>0);for(const claim of result.claims){assert.ok(result.source.includes(claim.text));assert.ok(result.draft.includes(claim.text))}for(const row of result.trace)assert.ok(result.source.includes(row.claim));});
test('structured employer sections preserve degree abbreviations, alternatives and unknown eligibility',()=>{const r=runtime();const out=r.run(String.raw`withCalibrationProfile(calibrationProfile({skills:['SolidWorks'],resumeText:''}),()=>{const j=calibrationJob({company:'Example Co',degreeFields:['Mechanical','Physics','Mathematics'],desc:'Example Co builds satellites.\nRequirements\nHold a four-year B.S. degree or currently pursuing a M.S. in mechanical engineering or physics.\nExperience with SolidWorks\nExperience with GD+T and engineering drawings\nBonus\nExperience with surface modeling\nSMS Terms of Service\nWe may send you messages.'});return {nodes:jobRequirementGraph(j).nodes,map:structuredRequirementMap(j),html:evidenceMapHtml(j)}})`);assert.ok(!out.nodes.some(x=>x.text.includes('builds satellites')));assert.ok(!out.nodes.some(x=>x.text.includes('send you messages')));assert.ok(out.map.some(x=>x.req.includes('four-year')&&!x.supported&&!x.known));assert.ok(out.map.some(x=>x.req.includes('GD+T')&&!x.supported));assert.ok(out.nodes.some(x=>x.text.includes('surface modeling')&&x.kind==='preferred'));assert.ok(out.html.includes('Needs review'));assert.equal(out.nodes.filter(x=>x.source==='Employer listing metadata'&&x.kind==='eligibility').length,0)});
test('degree metadata alternatives never require every listed major',()=>{const r=runtime();const map=r.run("withCalibrationProfile(calibrationProfile({major:'Physics',resumeText:''}),()=>structuredRequirementMap(calibrationJob({desc:'Engineering internship.',skills:[],degreeFields:['Mechanical','Physics','Mathematics']})))");assert.equal(map.filter(x=>x.kind==='eligibility').length,1);assert.ok(map.find(x=>x.kind==='eligibility').supported)});
test('legacy calibration runs against the final hardened matcher',()=>{const r=runtime();assert.equal(r.ctx.window.internAIMatchCalibrationResult.passed,true)});

for(const [major,requirement] of [['Biomechanical Engineering','Mechanical'],['Biochemical Engineering','Chemical'],['Electromechanical Engineering','Electrical']])test(`${major} is not silently equated to ${requirement}`,()=>{const r=runtime();r.ctx.major=major;r.ctx.requirement=requirement;const out=r.run("withCalibrationProfile(calibrationProfile({major}),()=>eligibilitySupport({text:'Pursuing a '+requirement+' Engineering degree',kind:'eligibility'}))");assert.equal(out.known,false);assert.equal(out.strength,0)});
for(const requirement of ['Minimum GPA 4.5 out of 5','Minimum GPA 3.0 on a 4.5 scale','Minimum GPA 10','Minimum GPA 3.0/10'])test(`nonstandard GPA requires review: ${requirement}`,()=>{const r=runtime();r.ctx.requirement=requirement;const out=r.run("withCalibrationProfile(calibrationProfile({gpa:'3.8'}),()=>eligibilitySupport({text:requirement,kind:'eligibility'}))");assert.equal(out.known,false)});
test('4.0 GPA scale is supported and full threshold precision is preserved',()=>{const r=runtime();assert.equal(r.run("withCalibrationProfile(calibrationProfile({gpa:'3.33'}),()=>eligibilitySupport({text:'Minimum GPA 3.333 out of 4.0',kind:'eligibility'}).strength)"),0);assert.equal(r.run("withCalibrationProfile(calibrationProfile({gpa:'3.8'}),()=>eligibilitySupport({text:'Minimum GPA 3.0/4.0',kind:'eligibility'}).strength)"),1)});
test('conjunctive degrees and professional experience duration are not credited from major',()=>{const r=runtime();for(const text of ['Pursuing Mechanical and Electrical Engineering degrees','Mechanical Engineering degree and 2 years professional experience']){r.ctx.requirement=text;assert.equal(r.run("withCalibrationProfile(calibrationProfile({major:'Mechanical Engineering'}),()=>eligibilitySupport({text:requirement,kind:'eligibility'}).known)"),false)}});
