const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {runtime}=require('./runtime.cjs');
const files=JSON.parse(fs.readFileSync('tests/script-order.json','utf8'));
function setup(){const r=runtime(files);r.run("fixture={format:'internai-workspace',workspace:{...structuredClone(defaultState),profile:{...structuredClone(defaultState.profile),name:'Recovered',resumeText:'Built a CAD model with SolidWorks.'},apps:[{id:'a1',company:'Example',title:'Intern',status:'Applied',notes:'My notes',draft:'Reviewed draft',statusHistory:[{from:'Preparing',to:'Applied',at:'2026-09-22T00:00:00Z'}]}],saved:['job-1']}}; originalProfile=state.profile; originalData=workspaceData(state); originalSession=workspaceRestoreSession()");return r}
test('backup restores notes, drafts, statuses and resume evidence',()=>{const r=setup();r.run('next=decodeWorkspaceBackup(JSON.stringify(fixture));restoreWorkspaceBackup(next,originalProfile,originalData,originalSession)');assert.equal(r.run('state.profile.name'),'Recovered');assert.equal(r.run('state.apps[0].draft'),'Reviewed draft');assert.equal(r.run('state.apps[0].statusHistory[0].to'),'Applied');assert.equal(r.run('state.profile.careerGraph.version'),3);assert.ok(r.storage.has('internai-before-restore:anonymous'));assert.equal(JSON.parse(r.storage.get('internai-demo')).profile.name,'Recovered')});
test('backup rejects malformed, oversized, future-version and unsafe IDs',()=>{const r=setup();for(const text of ['not json','{}','x'.repeat(5*1024*1024+1)]){r.ctx.input=text;assert.throws(()=>r.run('decodeWorkspaceBackup(input)'))}for(const edit of ["fixture.workspace.version=999","fixture.workspace.profile.skills={bad:true}","fixture.workspace.apps[0].id=\"x');alert(1);//\"","fixture.workspace.apps[0].notes={bad:true}","fixture.workspace.saved=[{}]"]){const q=setup();q.run(edit);assert.throws(()=>q.run('decodeWorkspaceBackup(JSON.stringify(fixture))'))}});
test('backup ignores derived caches and unrecognized fields and disables unsafe links',()=>{const r=setup();r.run("fixture.workspace.profile.careerGraph={version:3,claims:[{text:'Invented'}]};fixture.workspace.profile.evidence=[{claim:'Invented'}];fixture.workspace.importedJobs=[{id:'job-1',imported:true,title:'Role',applyUrl:'javascript:alert(1)'}];fixture.workspace.accountToken='untrusted';next=decodeWorkspaceBackup(JSON.stringify(fixture))");assert.equal(r.run('next.importedJobs[0].applyUrl'),'');assert.equal(r.run('next.accountToken'),undefined);assert.equal(r.run('next.profile.evidence.length'),0)});
test('backup cannot replace edits made after preview',()=>{const r=setup();r.run("state.profile.name='New edit';persist();next=decodeWorkspaceBackup(JSON.stringify(fixture))");assert.throws(()=>r.run('restoreWorkspaceBackup(next,originalProfile,originalData,originalSession)'));assert.equal(r.run('state.profile.name'),'New edit')});
test('backup cannot cross an account transition even if profile reference is unchanged',()=>{const r=setup();r.run("internEpoch++;next=decodeWorkspaceBackup(JSON.stringify(fixture))");assert.throws(()=>r.run('restoreWorkspaceBackup(next,originalProfile,originalData,originalSession)'))});
test('storage failure before or during restore preserves original workspace',()=>{for(const failAt of [1,2]){const r=setup();r.run("next=decodeWorkspaceBackup(JSON.stringify(fixture))");const originalSet=r.ctx.localStorage.setItem;let count=0;r.ctx.localStorage.setItem=(k,v)=>{if(++count===failAt)throw Error('Quota');originalSet(k,v)};assert.throws(()=>r.run('restoreWorkspaceBackup(next,originalProfile,originalData,originalSession)'));assert.equal(r.run('state.profile===originalProfile'),true);assert.equal(r.run('state.profile.name'),'')}});
test('cloud conflicts and stale tabs prevent restoration',()=>{for(const edit of ["internTabStale=true","internUser={id:'A'};internCloudConflict=true;localStorage.setItem('internai-local-owner','A')"]){const r=setup();r.run(edit);assert.equal(r.run('workspaceRestoreAllowed()'),false)}});

test('failure marking cloud sync pending rolls back the locally written replacement',()=>{const r=setup();r.run("internUser={id:'A'};internCloudReady=true;localStorage.setItem('internai-local-owner','A');originalSession=workspaceRestoreSession();next=decodeWorkspaceBackup(JSON.stringify(fixture))");const originalSet=r.ctx.localStorage.setItem;let count=0;r.ctx.localStorage.setItem=(k,v)=>{if(++count===3)throw Error('Quota');originalSet(k,v)};assert.throws(()=>r.run('restoreWorkspaceBackup(next,originalProfile,originalData,originalSession)'));assert.equal(r.run('state.profile===originalProfile'),true);assert.equal(JSON.parse(r.storage.get('internai-demo')).profile.name,'')});
