const test=require('node:test'),assert=require('node:assert/strict');
const {runtime}=require('./runtime.cjs');
test('both employer feeds start together and report partial failures with timestamps',async()=>{
 const r=runtime();r.run('jobs=dashboard=()=>{}');let release;const held=new Promise(resolve=>release=resolve),calls=[];
 r.ctx.fetch=async url=>{calls.push(url);if(url.includes('midwest'))throw Error('unavailable');await held;return{ok:true,json:async()=>({jobs:[{id:'one',live:true,applyUrl:'https://example.com/job'}],updatedAt:'2026-09-01T00:00:00Z',partial:true})}};
 const pending=r.run('loadLiveJobs(true)');assert.equal(calls.length,2);release();await pending;
 assert.equal(r.run('jobsData[0].fetchedAt'),'2026-09-01T00:00:00Z');assert.match(r.run('feedStatusText()'),/Results may be incomplete/);
});
test('feed merger deduplicates tracking variants',async()=>{const r=runtime();r.run('jobs=dashboard=()=>{}');r.ctx.fetch=async url=>({ok:true,json:async()=>({jobs:[{id:url,live:true,applyUrl:'https://example.com/job'+(url.includes('midwest')?'?utm_source=feed':'')}]})});await r.run('loadLiveJobs()');assert.equal(r.run('jobsData.length'),1)});
test('employer closure blocks handoff without treating an old listing as closed',()=>{const r=runtime();assert.equal(r.run("listingAvailability({live:true,closed:true,applyUrl:'https://example.com/job'}).available"),false);assert.equal(r.run("listingAvailability({live:true,postedAt:1,applyUrl:'https://example.com/job'}).available"),true)});
test('wrapped resume bullets stay under their project and retain all words',()=>{const r=runtime();const g=r.run("buildCareerGraph('PROJECTS\\nWater Pump Design — Course Project\\n• Designed a SolidWorks assembly to transport\\nwater vertically using a geared mechanism.\\n• Tested component clearance and recorded results.\\nEXPERIENCE\\nTechnical Assistant\\n• Repaired office equipment and documented maintenance.')");assert.equal(g.claims.length,3);assert.equal(g.claims[0].text,'Designed a SolidWorks assembly to transport water vertically using a geared mechanism.');assert.equal(g.claims[0].parentId,g.claims[1].parentId);assert.notEqual(g.claims[1].parentId,g.claims[2].parentId)});
test('unbulleted action sentence is evidence rather than a project heading',()=>{const r=runtime();const g=r.run("buildCareerGraph('Engine Design Project\\nDesigned a CAD assembly and tested fit')");assert.equal(g.nodes.length,1);assert.equal(g.claims.length,1)});
test('skill extraction does not find CAD inside Cascade or academic',()=>{const r=runtime();assert.equal(r.run("evidenceSkillHits('Cascade academic program').includes('CAD')"),false);assert.equal(r.run("evidenceSkillHits('SolidWorks (CAD), GD+T').includes('CAD')"),true);assert.equal(r.run("evidenceSkillHits('SolidWorks (CAD), GD+T').includes('GD&T')"),true)});
// Paraphrased boundary cases observed in Foth's employer posting:
// https://jobs.lever.co/foth/6cc70042-0140-4979-9878-828edf973a83 (reviewed 2026-09-21)
test('required qualifications and primary responsibilities retain distinct kinds',()=>{const r=runtime();const nodes=r.run("jobRequirementGraph(calibrationJob({skills:[],degreeFields:[],desc:'Primary Responsibilities:\\nDesign CAD components\\nRequired Qualifications:\\nPursuing mechanical engineering through an ABET-accredited program\\nPreferred Qualifications:\\nElectrical Engineering degree preferred'})).nodes");assert.equal(nodes.find(n=>n.text==='Design CAD components').kind,'responsibility');assert.equal(nodes.find(n=>n.text.includes('ABET')).kind,'eligibility');assert.equal(nodes.find(n=>n.text.includes('Electrical')).kind,'preferred')});
test('major alone cannot verify accreditation and a preferred degree is not a hard rejection',()=>{const r=runtime();const out=r.run("withCalibrationProfile(calibrationProfile(),()=>structuredRequirementMap(calibrationJob({skills:[],degreeFields:[],desc:'Required Qualifications:\\nPursuing mechanical engineering through an ABET-accredited program\\nPreferred Qualifications:\\nElectrical Engineering degree preferred'})))");assert.equal(out.find(n=>n.req.includes('ABET')).known,false);assert.ok(out.find(n=>n.req.includes('Electrical')).kind==='preferred')});
test('copy reads the current editor and reports clipboard failures honestly',async()=>{const r=runtime(),messages=[],copied=[];r.ctx.messages=messages;r.run('toast=m=>messages.push(m)');r.ctx.document.getElementById=id=>({value:id==='coverDraft'?'Edited letter':'Old preview'});r.ctx.navigator.clipboard={writeText:async text=>copied.push(text)};await r.run("copyKitText('coverPreview')");assert.deepEqual(copied,['Edited letter']);r.ctx.navigator.clipboard.writeText=async()=>{throw Error('denied')};await r.run("copyKitText('coverPreview')");assert.match(messages.at(-1),/Copy unavailable/)});
test('draft edits persist without requiring a separate save click',()=>{const r=runtime();r.run("const a=ensureApplication(seedJobs[0]);saveKitField(a.id,'draft','User-edited letter');state=load()");assert.equal(r.run('state.apps[0].draft'),'User-edited letter')});
test('tailored output excludes internal review instructions while notes retain provenance',()=>{const r=runtime();assert.equal(r.run('tailoredResumeDraft(seedJobs[0])').includes('REVIEW NOTE'),false);assert.ok(r.run('tailoredResumeNotes(seedJobs[0])').includes('CHANGES MADE'))});

test('diagnostics exclude source errors, profile fields, and resume text',()=>{const r=runtime();r.run("state.profile.name='Private Name';state.profile.resumeText='PRIVATE RESUME';recordDiagnostic('script_error');recordDiagnostic('PRIVATE RESUME')");const text=r.run('diagnosticsText()');assert.ok(text.includes('script_error'));assert.ok(!text.includes('Private Name'));assert.ok(!text.includes('PRIVATE RESUME'))});
test('browser entry point and VM harness use the same script dependency order',()=>{const fs=require('node:fs'),html=fs.readFileSync('index.html','utf8'),actual=[...html.matchAll(/<script src="(js\/[^\"]+)"/g)].map(m=>m[1]);assert.deepEqual(actual,JSON.parse(fs.readFileSync('tests/script-order.json','utf8')))});

test('background feed completion does not replace an in-progress import or draft',async()=>{const r=runtime();r.run("internActiveView='importJob';jobs=dashboard=()=>{throw Error('Unexpected navigation')}");r.ctx.fetch=async()=>({ok:true,json:async()=>({jobs:[]})});await r.run('loadLiveJobs(true)');assert.equal(r.run('internActiveView'),'importJob')});
