const test=require('node:test'),assert=require('node:assert/strict');const {runtime}=require('./runtime.cjs');
test('failed core plus successful Midwest has no sample jobs in live feed',async()=>{const r=runtime();r.run('dashboard=function(){};jobs=function(){}');r.ctx.fetch=async url=>{if(url.includes('midwest'))return {ok:true,json:async()=>({jobs:[{id:'live',applyUrl:'https://example.com/job',live:true}]})};throw Error('offline')};await r.run('loadLiveJobs()');assert.equal(r.run('jobsSource'),'live');assert.equal(r.run('jobsData.length'),1);assert.equal(r.run('jobsData[0].id'),'live')});
test('concurrent Discover refreshes share requests',async()=>{const r=runtime();r.run('dashboard=function(){};jobs=function(){}');let calls=0;r.ctx.fetch=async()=>{calls++;return{ok:true,json:async()=>({jobs:[]})}};await Promise.all([r.run('loadLiveJobs()'),r.run('loadLiveJobs()')]);assert.equal(calls,2)});
test('failed refresh restores explicitly labeled, discoverable sample jobs',async()=>{const r=runtime();r.run("dashboard=function(){};jobs=function(){};jobsData=[{id:'old-live'}];jobsSource='live';jobsLoaded=true");await r.run('loadLiveJobs(true)');assert.equal(r.run('jobsSource'),'fallback');assert.equal(r.run('jobsData.every(j=>j.source===\'Sample fallback\')'),true);assert.ok(r.run('filteredJobs().length')>0)});
test('apply links reject scripts, credentials, and insecure protocols',()=>{const r=runtime();for(const url of ['javascript:alert(1)','data:text/html,test','http://example.com','https://user:password@example.com']){r.ctx.input=url;assert.equal(r.run('safeApplyUrl(input)'),'')}assert.equal(r.run("safeApplyUrl('https://example.com/job')"),'https://example.com/job')});
test('PDF extraction cannot write into an account switched during parsing',async()=>{const r=runtime();let release;r.ctx.resumePromise=new Promise(resolve=>release=resolve);r.run('extractStructuredPdfText=()=>resumePromise');r.ctx.file={name:'sample.pdf',type:'application/pdf'};const parsing=r.run('parseResumeFile(file)');r.run('state=structuredClone(defaultState)');release('Mechanical Engineering project with SolidWorks CAD and documented testing.');await parsing;assert.equal(r.run('state.profile.resumeText'),'')});
test('PDF line reconstruction preserves ordering',()=>{const r=runtime();const lines=r.run("pdfItemsToLines([{str:'second',transform:[0,0,0,0,0,10]},{str:'line',transform:[0,0,0,0,40,20]},{str:'first',transform:[0,0,0,0,0,20]}])");assert.equal(JSON.stringify(lines),'["first line","second"]')});
test('application status, notes, drafts, source snapshot persist through reload',()=>{const r=runtime();r.run("applications=function(){};const a=ensureApplication(seedJobs[0]);a.notes='Follow up';a.draft='Reviewed source draft';updateStatus(a.id,'Applied');state=load()");assert.equal(r.run('state.apps[0].status'),'Applied');assert.equal(r.run('state.apps[0].notes'),'Follow up');assert.equal(r.run('state.apps[0].draft'),'Reviewed source draft');assert.equal(r.run('state.apps[0].jobSnapshot.id'),'j1');assert.ok(r.run('state.apps[0].submittedAt'))});

test('application status transitions retain timestamped history',()=>{const r=runtime();r.run("applications=function(){};const a=ensureApplication(seedJobs[0]);updateStatus(a.id,'Applied');updateStatus(a.id,'Interview');state=load()");assert.equal(r.run('state.apps[0].status'),'Interview');assert.equal(r.run('state.apps[0].statusHistory.length'),2);assert.equal(r.run("state.apps[0].statusHistory[0].to"),'Applied');assert.equal(r.run("state.apps[0].statusHistory[1].to"),'Interview');assert.ok(r.run('state.apps[0].submittedAt'));assert.ok(r.run('state.apps[0].interviewAt'))});
