const test=require('node:test'),assert=require('node:assert/strict');const {runtime}=require('./runtime.cjs');
test('failed core plus successful Midwest has no sample jobs in live feed',async()=>{const r=runtime();r.run('dashboard=function(){};jobs=function(){}');r.ctx.fetch=async url=>{if(url.includes('midwest'))return {ok:true,json:async()=>({jobs:[{id:'live',applyUrl:'https://example.com/job',live:true}]})};throw Error('offline')};await r.run('loadLiveJobs()');assert.equal(r.run('jobsSource'),'live');assert.equal(r.run('jobsData.length'),1);assert.equal(r.run('jobsData[0].id'),'live')});
test('concurrent Discover refreshes share requests',async()=>{const r=runtime();r.run('dashboard=function(){};jobs=function(){}');let calls=0;r.ctx.fetch=async()=>{calls++;return{ok:true,json:async()=>({jobs:[]})}};await Promise.all([r.run('loadLiveJobs()'),r.run('loadLiveJobs()')]);assert.equal(calls,2)});
test('failed refresh restores explicitly labeled, discoverable sample jobs',async()=>{const r=runtime();r.run("dashboard=function(){};jobs=function(){};jobsData=[{id:'old-live'}];jobsSource='live';jobsLoaded=true");await r.run('loadLiveJobs(true)');assert.equal(r.run('jobsSource'),'fallback');assert.equal(r.run('jobsData.every(j=>j.source===\'Sample fallback\')'),true);assert.ok(r.run('filteredJobs().length')>0)});
test('apply links reject scripts, credentials, and insecure protocols',()=>{const r=runtime();for(const url of ['javascript:alert(1)','data:text/html,test','http://example.com','https://user:password@example.com']){r.ctx.input=url;assert.equal(r.run('safeApplyUrl(input)'),'')}assert.equal(r.run("safeApplyUrl('https://example.com/job')"),'https://example.com/job')});
test('PDF extraction cannot write into an account switched during parsing',async()=>{const r=runtime();let release;r.ctx.resumePromise=new Promise(resolve=>release=resolve);r.run('extractStructuredPdfText=()=>resumePromise');r.ctx.file={name:'sample.pdf',type:'application/pdf'};const parsing=r.run('parseResumeFile(file)');r.run('state=structuredClone(defaultState)');release('Mechanical Engineering project with SolidWorks CAD and documented testing.');await parsing;assert.equal(r.run('state.profile.resumeText'),'')});
test('PDF line reconstruction preserves ordering',()=>{const r=runtime();const lines=r.run("pdfItemsToLines([{str:'second',transform:[0,0,0,0,0,10]},{str:'line',transform:[0,0,0,0,40,20]},{str:'first',transform:[0,0,0,0,0,20]}])");assert.equal(JSON.stringify(lines),'["first line","second"]')});
test('application status, notes, drafts, source snapshot persist through reload',()=>{const r=runtime();r.run("applications=function(){};const a=ensureApplication(seedJobs[0]);a.notes='Follow up';a.draft='Reviewed source draft';updateStatus(a.id,'Applied');state=load()");assert.equal(r.run('state.apps[0].status'),'Applied');assert.equal(r.run('state.apps[0].notes'),'Follow up');assert.equal(r.run('state.apps[0].draft'),'Reviewed source draft');assert.equal(r.run('state.apps[0].jobSnapshot.id'),'j1');assert.ok(r.run('state.apps[0].submittedAt'))});

test('application status transitions retain timestamped history',()=>{const r=runtime();r.run("applications=function(){};const a=ensureApplication(seedJobs[0]);updateStatus(a.id,'Applied');updateStatus(a.id,'Interview');state=load()");assert.equal(r.run('state.apps[0].status'),'Interview');assert.equal(r.run('state.apps[0].statusHistory.length'),2);assert.equal(r.run("state.apps[0].statusHistory[0].to"),'Applied');assert.equal(r.run("state.apps[0].statusHistory[1].to"),'Interview');assert.ok(r.run('state.apps[0].submittedAt'));assert.ok(r.run('state.apps[0].interviewAt'))});

test('legacy workspace state migrates to current schema without losing applications',()=>{const r=runtime();r.storage.set('internai-demo',JSON.stringify({profile:{name:'Legacy'},saved:'bad',apps:[{id:'a',company:'C',title:'T'}]}));r.run('state=load()');assert.equal(r.run('state.version'),2);assert.equal(r.run('state.profile.name'),'Legacy');assert.equal(r.run('state.saved.length'),0);assert.equal(r.run("state.apps[0].status"),'Interested');assert.equal(r.run('state.apps[0].statusHistory.length'),0)});
test('detail-page status changes retain history and first milestone dates',()=>{const r=runtime();r.run("ensureApplication(seedJobs[0])");const fields={astatus:{value:'Applied'},anotes:{value:'QA note'}};r.ctx.document.getElementById=id=>fields[id]||{classList:{add(){},remove(){}},textContent:''};r.run('saveApp(state.apps[0].id)');const first=r.run('state.apps[0].submittedAt');fields.astatus.value='Interview';r.run('saveApp(state.apps[0].id)');assert.equal(r.run('state.apps[0].statusHistory.length'),2);assert.equal(r.run('state.apps[0].submittedAt'),first);assert.ok(r.run('state.apps[0].interviewAt'));assert.equal(r.run('load().apps[0].notes'),'QA note')});
test('fallback cards and shortlist disclose samples; multi-season explanation uses selected term',()=>{const r=runtime();assert.ok(r.run('jobHtml(seedJobs[0])').includes('Sample — not a real opening'));assert.ok(r.run('bestOpportunityHtml(seedJobs[0])').includes('Sample — not a real opening'));const reason=r.run("opportunityReason({...seedJobs[0],season:['Spring','Summer'],year:2027},matchBreakdown(seedJobs[0]))");assert.ok(reason.includes('target term confirmed: Summer 2027'))});
test('reopening submission step preserves an existing outcome and its history',()=>{const r=runtime();r.run("savePrep=()=>{};openApplyStep=()=>{};applications=()=>{};const a=ensureApplication(seedJobs[0]);updateStatus(a.id,'Interview');readyToApply(a.id)");assert.equal(r.run('state.apps[0].status'),'Interview');assert.equal(r.run('state.apps[0].statusHistory.length'),1)});

test('external application flow uses the same URL safety gate as rendered links',()=>{const r=runtime();const opened=[];r.ctx.window.open=(...args)=>opened.push(args);r.run("const a=ensureApplication(seedJobs[0]);a.jobSnapshot.applyUrl='https://user:password@example.com/app';openExternalApply(a.id)");assert.equal(opened.length,0);r.run("state.apps[0].jobSnapshot.applyUrl='https://example.com/app';openExternalApply(state.apps[0].id)");assert.equal(opened.length,1);assert.equal(opened[0][0],'https://example.com/app');assert.equal(opened[0][2],'noopener,noreferrer')});

test('repeating a status does not duplicate history or overwrite its first milestone date',()=>{const r=runtime();r.run("const a=ensureApplication(seedJobs[0]);recordStatus(a,'Applied');const first=a.submittedAt;recordStatus(a,'Applied')");assert.equal(r.run('state.apps[0].statusHistory.length'),1);assert.equal(r.run('state.apps[0].submittedAt'),r.run('first'))});

 test('sample submission screen explains missing link and offers Discover instead of submission',()=>{const r=runtime();const page={innerHTML:''};r.ctx.document.getElementById=()=>page;r.run("const a=ensureApplication(seedJobs.find(j=>j.company==='Cascade Energy'));openApplyStep(a.id)");assert.ok(page.innerHTML.includes('Sample — not a real opening'));assert.ok(page.innerHTML.includes('Back to Discover'));assert.ok(!page.innerHTML.includes('Open application site'));assert.ok(!page.innerHTML.includes('I submitted it'));});

test('listing availability distinguishes live links, unavailable live roles, and samples',()=>{const r=runtime();assert.equal(r.run("listingAvailability({live:true,applyUrl:'https://example.com/job'}).available"),true);assert.equal(r.run("listingAvailability({live:true,applyUrl:'javascript:alert(1)'}).label"),'Application link unavailable');assert.equal(r.run("listingAvailability(seedJobs[0]).label"),'Sample listing')});

test('listing freshness warns on old dated postings without falsely declaring them expired',()=>{const r=runtime();r.ctx.old=r.ctx.Date.now()-121*86400000;r.ctx.fresh=r.ctx.Date.now()-7*86400000;assert.equal(r.run("listingAvailability({live:true,applyUrl:'https://example.com/job',postedAt:old}).label"),'Older employer listing');assert.equal(r.run("listingAvailability({live:true,applyUrl:'https://example.com/job',postedAt:old}).available"),true);assert.equal(r.run("listingAvailability({live:true,applyUrl:'https://example.com/job',postedAt:fresh}).label"),'Employer application')});
