const SOURCES=[
  {provider:'lever',site:'foth',company:'Foth'},{provider:'lever',site:'hermeus',company:'Hermeus'},{provider:'lever',site:'nexuse-group',company:'Nexus Engineering Group'},{provider:'lever',site:'shieldai',company:'Shield AI'},{provider:'lever',site:'CesiumAstro',company:'CesiumAstro'},
  {provider:'greenhouse',site:'andurilindustries',company:'Anduril Industries'},{provider:'greenhouse',site:'astranis',company:'Astranis'},{provider:'greenhouse',site:'stokespacetechnologies',company:'Stoke Space'},{provider:'greenhouse',site:'freeformfuturecorp',company:'Freeform'},{provider:'greenhouse',site:'kairospower',company:'Kairos Power'},{provider:'greenhouse',site:'graviticsinc',company:'Gravitics'},{provider:'greenhouse',site:'amca',company:'Amca'},{provider:'greenhouse',site:'spacex',company:'SpaceX'},{provider:'greenhouse',site:'vardaspace',company:'Varda Space Industries'},{provider:'greenhouse',site:'awetomaton',company:'Awetomaton'},
  {provider:'lincoln',site:'early-talent',company:'Lincoln Electric'}
];
const SKILLS=[['SolidWorks',/solid\s?works/i],['Onshape',/onshape/i],['CAD',/\bCAD\b|computer[- ]aided design|autocad|inventor|solid\s?edge/i],['Python',/\bpython\b/i],['JavaScript',/javascript/i],['Excel',/\bexcel\b|microsoft excel/i],['Mechanical Design',/mechanical design|machine design|component design/i],['Mechanical Systems',/mechanical systems?|mechanical assembl/i],['Thermodynamics',/thermodynamics?|heat transfer/i],['Data Analysis',/data analysis|analy[sz]e data/i],['Process Optimization',/process optimization|process improvement|continuous improvement/i],['Project Management',/project management/i],['Team Collaboration',/cross[- ]functional|collaborat|multidisciplinary/i],['Prototyping',/prototyp|rapid iteration/i],['GD&T',/GD&T|geometric dimension/i],['Systems Engineering',/systems engineering|system integration/i],['Testing',/\btest(?:ing)?\b|verification|validation|test plan/i],['Manufacturing',/manufactur|production line/i],['Technical Writing',/technical (?:documentation|writing)|engineering documentation/i],['Requirements',/requirements? (?:development|management|analysis)|system requirements?/i],['Lean',/\blean\b|six sigma/i]];
const DEGREE_FIELDS=[['Mechanical',/mechanical engineering/i],['Aerospace',/aerospace engineering|aeronautical engineering/i],['Manufacturing',/manufacturing engineering/i],['Industrial',/industrial engineering/i],['Systems',/systems engineering/i],['Electrical',/electrical engineering/i],['Computer',/computer engineering/i],['Software',/software engineering|computer science/i],['Chemical',/chemical engineering/i],['Civil',/civil engineering/i],['Biomedical',/biomedical engineering/i],['Materials',/materials (?:science|engineering)|materials science and engineering/i],['Physics',/\bphysics\b/i],['Mathematics',/\bmathematics\b|\bmath\b/i]];
function stripHtml(v=''){return String(v).replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&(?:#x?[0-9a-f]+|\w+);/gi,' ').replace(/\s+/g,' ').trim()}
function skillsFrom(t=''){const f=SKILLS.filter(([,r])=>r.test(t)).map(([n])=>n);return f.length?f.slice(0,10):['Engineering']}
function degreeFieldsFrom(t=''){return DEGREE_FIELDS.filter(([,r])=>r.test(t)).map(([n])=>n)}
function isInternshipText(title='',extra=''){const b=`${title} ${extra}`.toLowerCase();return /intern|co-?op|seasonal/.test(b)&&/engineer|mechanical|manufacturing|structures?|propulsion|systems?|test|controls?|process|piping|electrical|design|supply chain|avionics|flight software|gnc|automation|cad|hardware/.test(b)&&!/202[0-6]|202[8-9]/.test(title)}
function seasonFromText(v=''){const t=String(v).toLowerCase(),s=[];if(t.includes('spring'))s.push('Spring');if(t.includes('summer'))s.push('Summer');if(t.includes('fall')||t.includes('autumn'))s.push('Fall');if(t.includes('winter'))s.push('Winter');return s.length?s:['Unspecified']}
function inferMode(raw='',loc='',content=''){const p=`${raw} ${loc}`.toLowerCase();if(/\bremote\b/.test(p))return'Remote';if(/\bhybrid\b/.test(p))return'Hybrid';const t=String(content).toLowerCase();if(/(?:work|position|role|internship) (?:is |will be )?(?:fully )?remote\b|remote (?:work|position|role|internship)\b/.test(t))return'Remote';if(/(?:work|position|role|internship) (?:is |will be )?hybrid\b|hybrid (?:work|position|role|internship)\b/.test(t))return'Hybrid';return'On-site'}
function norm({id,company,title,location,mode,season,full,desc,source,applyUrl,provider,postedAt}){return{id,company,title,location:location||'Location not listed',mode,season,skills:skillsFrom(full),degreeFields:degreeFieldsFrom(full),preferred:[],deadline:'Not listed',source,applyUrl,desc:(desc||'See the employer listing for full role details.').slice(0,1400),live:true,provider,postedAt:postedAt||null}}
function normalizeLever(j,s){const text=stripHtml(j.descriptionPlain||j.description||''),lists=Array.isArray(j.lists)?j.lists.map(x=>`${x.text||''} ${stripHtml(x.content||'')}`).join(' '):'',full=`${j.text||''} ${text} ${lists}`,location=j.categories?.location||j.categories?.allLocations?.join(' / ')||'Location not listed';return norm({id:`lever-${s.site}-${j.id}`,company:s.company,title:j.text||'Engineering Internship',location,mode:inferMode(j.workplaceType||j.categories?.workplaceType||'',location,full),season:seasonFromText(full),full,desc:text||stripHtml(lists),source:'Live · employer Lever board',applyUrl:j.hostedUrl||j.applyUrl||'',provider:'Lever',postedAt:j.createdAt||null})}
async function fetchLever(s){const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000);try{const r=await fetch(`https://api.lever.co/v0/postings/${encodeURIComponent(s.site)}?mode=json`,{headers:{accept:'application/json','user-agent':'InternAI/1.0'},signal:c.signal});if(!r.ok)throw new Error(`${s.site}: ${r.status}`);const d=await r.json();return(Array.isArray(d)?d:[]).filter(j=>isInternshipText(j.text||'',`${j.categories?.commitment||''} ${j.categories?.team||''}`)).map(j=>normalizeLever(j,s))}finally{clearTimeout(timer)}}
function normalizeGreenhouse(j,s){const title=j.title||'Engineering Internship',content=stripHtml(j.content||''),location=j.location?.name||'Location not listed',dept=Array.isArray(j.departments)?j.departments.map(x=>x.name||'').join(' '):'',office=Array.isArray(j.offices)?j.offices.map(x=>x.name||'').join(' '):'',full=`${title} ${dept} ${office} ${content}`;return norm({id:`greenhouse-${s.site}-${j.id}`,company:s.company,title,location,mode:inferMode('',location,content),season:seasonFromText(full),full,desc:content,source:'Live · employer Greenhouse board',applyUrl:j.absolute_url||'',provider:'Greenhouse',postedAt:j.updated_at?Date.parse(j.updated_at):null})}
async function fetchGreenhouse(s){const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000);try{const r=await fetch(`https://boards-api.greenhouse.io/v1/boards/${encodeURIComponent(s.site)}/jobs?content=true`,{headers:{accept:'application/json','user-agent':'InternAI/1.0'},signal:c.signal});if(!r.ok)throw new Error(`${s.site}: ${r.status}`);const d=await r.json();return(Array.isArray(d.jobs)?d.jobs:[]).filter(j=>isInternshipText(j.title||'',`${(j.departments||[]).map(x=>x.name||'').join(' ')} ${stripHtml(j.content||'')}`)).map(j=>normalizeGreenhouse(j,s))}finally{clearTimeout(timer)}}
async function fetchLincoln(s){const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000);try{const base='https://jobs.lincolnelectric.com',r=await fetch(`${base}/go/Student-%26-Grad-Jobs/2374400/`,{headers:{accept:'text/html','user-agent':'InternAI/1.0'},signal:c.signal});if(!r.ok)throw new Error(`lincoln: ${r.status}`);const html=await r.text(),seen=new Set(),jobs=[];const re=/<a[^>]+href=["']([^"']*\/job\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){let url=m[1];if(url.startsWith('/'))url=base+url;else if(!/^https?:/i.test(url))continue;if(seen.has(url))continue;const title=stripHtml(m[2]);if(!isInternshipText(title,''))continue;seen.add(url);const locMatch=title.match(/\(([^()]+,\s*[A-Z]{2})\)/i);const location=locMatch?locMatch[1].replace(/\bOh\b/i,'OH').replace(/\bMi\b/i,'MI'):(/Euclid/i.test(title)?'Cleveland, OH':'Location listed on employer page');const full=`${title} Lincoln Electric engineering manufacturing automation mechanical design testing`;jobs.push(norm({id:`lincoln-${Buffer.from(url).toString('base64').slice(-18).replace(/\W/g,'')}`,company:s.company,title,location,mode:'On-site',season:seasonFromText(title),full,desc:'Official Lincoln Electric early-talent listing. Open the employer posting for complete responsibilities and qualifications.',source:'Live · Lincoln Electric careers',applyUrl:url,provider:'Lincoln Electric Careers',postedAt:null}))}return jobs}finally{clearTimeout(timer)}}
async function fetchSource(s){if(s.provider==='greenhouse')return fetchGreenhouse(s);if(s.provider==='lincoln')return fetchLincoln(s);return fetchLever(s)}
module.exports=async function handler(req,res){if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({error:'Method not allowed'})}const settled=await Promise.allSettled(SOURCES.map(fetchSource)),jobs=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]),unique=[...new Map(jobs.map(j=>[j.applyUrl||j.id,j])).values()].sort((a,b)=>(b.postedAt||0)-(a.postedAt||0));res.setHeader('Cache-Control','s-maxage=600, stale-while-revalidate=1800');return res.status(200).json({jobs:unique,count:unique.length,source:'public-employer-boards',providers:['Lever','Greenhouse','Lincoln Electric Careers'],employers:SOURCES.map(s=>s.company),updatedAt:new Date().toISOString(),partial:settled.some(x=>x.status==='rejected')})};
