const SOURCES=[
 {key:'crown',company:'Crown Equipment',kind:'html',url:'https://us-careers.crown.com/go/Co-op-and-Intern/7836800/'},
 {key:'lubrizol',company:'Lubrizol',kind:'html',url:'https://jobs.lubrizol.com/go/University-Student-Opportunities/2569700/'},
 {key:'snc',company:'Sierra Nevada Corporation',kind:'workday',origin:'https://snc.wd1.myworkdayjobs.com',tenant:'snc',site:'SNC_External_Career_Site'}
];
const SKILLS=[['CAD',/\bcad\b|computer[- ]aided|autocad|solidworks|creo|finite element|\bfea\b/i],['Mechanical Design',/mechanical design|product design|design and development|design through construction/i],['Testing',/\btest(?:ing)?\b|validation|verification|experimental/i],['Manufacturing',/manufactur|production|plant process/i],['Data Analysis',/data analysis|analy[sz](?:e|ing)|technical data/i],['Excel',/\bexcel\b/i],['Project Management',/project management|capital project/i],['Systems Engineering',/systems engineering|system integration|requirements/i],['Technical Writing',/technical documentation|reports|records/i],['Process Optimization',/process improvement|continuous improvement|process reviews?/i]];
const DEGREES=[['Mechanical',/mechanical engineering/i],['Manufacturing',/manufacturing engineering/i],['Industrial',/industrial engineering/i],['Systems',/systems engineering/i],['Electrical',/electrical engineering/i],['Computer',/computer engineering|computer science/i],['Aerospace',/aerospace|aeronautical/i],['Chemical',/chemical engineering/i]];
function strip(v=''){return String(v).replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<\/?(?:p|div|li|ul|ol|h[1-6]|br|section)\b[^>]*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/g,"'").replace(/&quot;/gi,'"').replace(/&(?:#x?[0-9a-f]+|\w+);/gi,' ').replace(/[^\S\n]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{2,}/g,'\n').trim()}
function skills(t){const a=SKILLS.filter(([,r])=>r.test(t)).map(([n])=>n);return a.length?a:['Engineering']}
function degrees(t){return DEGREES.filter(([,r])=>r.test(t)).map(([n])=>n)}
function relevant(title='',text=''){const t=`${title} ${text}`;return /\bintern(?:ship)?s?\b|\bco[ -]?op\b/i.test(title)&&/mechanical|manufacturing|engineer|systems?|test|quality|process|design|cad|hardware|materials/i.test(t)&&!/202[0-6]|202[8-9]/.test(title)}
function season(t=''){const a=[];if(/spring/i.test(t))a.push('Spring');if(/summer/i.test(t))a.push('Summer');if(/fall|autumn/i.test(t))a.push('Fall');if(/winter/i.test(t))a.push('Winter');return a.length?a:['Unspecified']}
function year(title='',text=''){const m=String(title).match(/\b(20(?:2[7-9]|3\d))\b/)||String(text).match(/(?:spring|summer|fall|autumn|winter)[ /-]*(20(?:2[7-9]|3\d))/i);return m?Number(m[1]):null}
function mode(text=''){return /\bremote\b/i.test(text)?'Remote':/\bhybrid\b/i.test(text)?'Hybrid':'On-site'}
function location(text=''){const m=String(text).match(/\b([A-Za-z][A-Za-z .'-]{1,40}),\s*([A-Z]{2})(?:,?\s*US)?(?:,?\s*\d{5}(?:-\d+)?)?/);return m?`${m[1].trim()}, ${m[2]}`:'Location listed on employer page'}
function norm({id,company,title,text,applyUrl,provider,postedAt,loc}){const full=`${title} ${loc||''} ${text}`;return{id,company,title,location:loc||location(text),mode:mode(full),season:season(full),year:year(title,full),skills:skills(full),degreeFields:degrees(full),preferred:[],deadline:'Not listed',source:`Live · ${provider}`,applyUrl,desc:text.slice(0,16000),live:true,provider,postedAt:postedAt||null}}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function worker(){while(next<items.length){const i=next++;try{out[i]={status:'fulfilled',value:await fn(items[i],i)}}catch(reason){out[i]={status:'rejected',reason}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
async function get(url,ms=6000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{accept:'text/html','user-agent':'InternAI/1.0'},signal:c.signal});if(!r.ok)throw new Error(`${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
async function detail(applyUrl,meta){try{const html=await get(applyUrl,4500),text=strip(html),title=strip((html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]||meta.title);return relevant(title,text)?norm({...meta,title,text,applyUrl}):null}catch{return null}}
async function fetchHtml(s){const html=await get(s.url),seen=new Set(),items=[],re=/<a[^>]+href=["']([^"']*\/job\/[^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&items.length<20){let u=m[1];if(u.startsWith('/'))u=new URL(u,s.url).href;else if(!/^https?:/i.test(u))continue;const title=strip(m[2]);if(seen.has(u)||!relevant(title,''))continue;seen.add(u);items.push({u,title})}const out=await mapLimit(items,5,({u,title})=>detail(u,{id:`${s.key}-${Buffer.from(u).toString('base64').slice(-18).replace(/\W/g,'')}`,company:s.company,title,provider:`${s.company} careers`,postedAt:null}));return out.flatMap(x=>x.status==='fulfilled'&&x.value?[x.value]:[])}
async function fetchSnc(s){const api=`${s.origin}/wday/cxs/${s.tenant}/${s.site}`,headers={'content-type':'application/json',accept:'application/json','user-agent':'InternAI/1.0'},c=new AbortController(),timer=setTimeout(()=>c.abort(),7000);let data;try{const r=await fetch(`${api}/jobs`,{method:'POST',headers,body:JSON.stringify({appliedFacets:{},limit:20,offset:0,searchText:'Summer 2027 intern'}),signal:c.signal});if(!r.ok)throw new Error(`${r.status}`);data=await r.json()}finally{clearTimeout(timer)}const rows=(data.jobPostings||[]).filter(x=>relevant(x.title||'',x.locationsText||'')&&x.externalPath).slice(0,16),out=await mapLimit(rows,5,async row=>{const dc=new AbortController(),dt=setTimeout(()=>dc.abort(),4500);try{const r=await fetch(`${api}${row.externalPath}`,{headers:{accept:'application/json','user-agent':'InternAI/1.0'},signal:dc.signal});if(!r.ok)return null;const d=await r.json(),info=d.jobPostingInfo||d,text=strip(info.jobDescription||''),title=row.title||info.title||'Engineering Intern';if(!relevant(title,text))return null;const applyUrl=`${s.origin}/en-US/${s.site}${row.externalPath}`;return norm({id:`snc-${info.jobReqId||Buffer.from(row.externalPath).toString('base64').slice(-14).replace(/\W/g,'')}`,company:s.company,title,text,applyUrl,provider:'SNC Workday',postedAt:info.startDate?Date.parse(info.startDate):null,loc:info.location||row.locationsText||location(text)})}finally{clearTimeout(dt)}});return out.flatMap(x=>x.status==='fulfilled'&&x.value?[x.value]:[])}
async function fetchSource(s){const started=Date.now();try{const jobs=s.kind==='workday'?await fetchSnc(s):await fetchHtml(s);return{ok:true,key:s.key,company:s.company,jobs,ms:Date.now()-started}}catch(error){return{ok:false,key:s.key,company:s.company,jobs:[],ms:Date.now()-started,error:String(error&&error.message||error)}}}
module.exports=async function handler(req,res){if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({error:'Method not allowed'})}const results=await Promise.all(SOURCES.map(fetchSource)),jobs=results.flatMap(x=>x.jobs),unique=[...new Map(jobs.map(j=>[j.applyUrl,j])).values()];res.setHeader('Cache-Control','s-maxage=600, stale-while-revalidate=1800');return res.status(200).json({jobs:unique,count:unique.length,source:'midwest-public-employer-boards',providers:['Crown Equipment careers','SNC Workday','Lubrizol careers'],employers:SOURCES.map(s=>s.company),partial:results.some(x=>!x.ok),sources:results.map(({key,company,ok,jobs,ms,error})=>({key,company,ok,count:jobs.length,ms,error:error||null})),updatedAt:new Date().toISOString()})};