const CHECKS=[
  {key:'lever-foth',provider:'Lever',company:'Foth',url:'https://api.lever.co/v0/postings/foth?mode=json',kind:'json'},
  {key:'greenhouse-spacex',provider:'Greenhouse',company:'SpaceX',url:'https://boards-api.greenhouse.io/v1/boards/spacex/jobs?content=false',kind:'json'},
  {key:'lincoln',provider:'Lincoln Electric Careers',company:'Lincoln Electric',url:'https://jobs.lincolnelectric.com/go/Student-%26-Grad-Jobs/2374400/',kind:'html',signal:/intern|co-?op|student/i},
  {key:'bwxt',provider:'BWXT Careers',company:'BWXT',url:'https://careers.bwxt.com/go/Recent-Grad-and-Student-Jobs/3930400/',kind:'html',signal:/intern|co-?op|student/i},
  {key:'oatey',provider:'Oatey Careers',company:'Oatey',url:'https://careers.oatey.com/search/searchjobs?uselocation=true',kind:'html',signal:/intern|co-?op|student/i},
  {key:'imeg',provider:'IMEG Workday',company:'IMEG',url:'https://imeg.wd1.myworkdayjobs.com/wday/cxs/imeg/Imeg_Careers/jobs',kind:'workday'},
  {key:'stryker',provider:'Stryker Careers',company:'Stryker',url:'https://careers.stryker.com/students-and-graduates',kind:'html',signal:/intern|student|graduate/i},
  {key:'crown',provider:'Crown Careers',company:'Crown Equipment',url:'https://us-careers.crown.com/go/Co-op-and-Intern/7836800/',kind:'html',signal:/summer\s+2027|co-?op|intern/i},
  {key:'lubrizol',provider:'Lubrizol Careers',company:'Lubrizol',url:'https://jobs.lubrizol.com/go/University-Students/2569900/',kind:'html',signal:/2027|co-?op|intern/i},
  {key:'snc',provider:'SNC Workday',company:'SNC',url:'https://snc.wd1.myworkdayjobs.com/wday/cxs/snc/SNC_External_Career_Site/jobs',kind:'workday'}
];
async function check(c){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000),started=Date.now();try{const options={headers:{accept:c.kind==='json'||c.kind==='workday'?'application/json':'text/html','user-agent':'InternAI/1.0'},signal:controller.signal};if(c.kind==='workday'){options.method='POST';options.headers['content-type']='application/json';options.body=JSON.stringify({appliedFacets:{},limit:5,offset:0,searchText:'intern'})}const r=await fetch(c.url,options),text=await r.text();let usable=r.ok&&text.length>80,count=null,signalFound=c.signal?c.signal.test(text):null;if(usable&&c.kind==='html'&&c.signal)usable=signalFound;if(usable&&c.kind==='json'){try{const d=JSON.parse(text);count=Array.isArray(d)?d.length:Array.isArray(d.jobs)?d.jobs.length:null}catch{usable=false}}if(usable&&c.kind==='workday'){try{const d=JSON.parse(text);count=Number.isFinite(Number(d.total))?Number(d.total):Array.isArray(d.jobPostings)?d.jobPostings.length:null;usable=Array.isArray(d.jobPostings)}catch{usable=false}}return{key:c.key,provider:c.provider,company:c.company,ok:usable,httpStatus:r.status,latencyMs:Date.now()-started,count,signalFound}}catch(e){return{key:c.key,provider:c.provider,company:c.company,ok:false,httpStatus:null,latencyMs:Date.now()-started,count:null,signalFound:null,error:e?.name==='AbortError'?'timeout':'request failed'}}finally{clearTimeout(timer)}}
module.exports=async function handler(req,res){if(req.method!=='GET'){res.setHeader('Allow','GET');return res.status(405).json({error:'Method not allowed'})}const results=await Promise.all(CHECKS.map(check)),healthy=results.filter(x=>x.ok).length;res.setHeader('Cache-Control','no-store');return res.status(healthy===results.length?200:207).json({healthy,total:results.length,allHealthy:healthy===results.length,results,checkedAt:new Date().toISOString(),note:'Connectivity and listing-signal diagnostics only; /api/jobs remains the source of normalized internship records.'})};